#!/usr/bin/env python
# encoding: utf-8
"""
fields.py - describes the SoftM table structure. Part of huSoftM.

Created by Maximillian Dornseif on 2007-03-18. Based on code named "MoftS" from Summer 2005.
Copyright (c) 2007, 2008 HUDORA GmbH. All rights reserved.
"""

__revision__ = "$Revision$"

MAPPINGDIR = {'MLP00': {# MPL Plätze
                        'LPPLTY': 'platztyp',
                        'LPBHBL': 'behaelterbelegung',
                        'LPBHMG': 'behaeltermenge',
                        'LPLGPL': 'lagerplatz',
                        'LPFPAR': 'artnr',
                        #'LPREIH': 'reihe',
                        #'LPFACH': 'fach',
                        #'LPRIEG': 'riegel',
                        'LPMINC': 'minmenge',
                        'LPMAXC': 'maxmenge',
                        'LPSPRC': 'sprungmenge',
                        'LPRSEN': 'einlagerungsrestriktion',
                        'LPRSAS': 'auslagerungsrestriktion',
                        'LPSPEZ': 'LPSPEZ',
                        #'LPDTAE': 'DatumAenderung',
                        #'LPSBAE': 'BearbeiterAenderung',
                        'LPKZSM': 'entnahmenurkleinersprungmenge',
                        'LPINFO': 'info',
                        'LPKZBL': 'belegung',
                        'LPBHBL': 'behaelterbelegung',
                        'LPBHMG': 'behaelteranzahl',
                        'LPAZFP': 'freieplaetze',
                        'LPKZFG': 'platzfreigabe',
                        'LPBHST': 'behaelterstandart',
                        'LPSTAT': 'status',
                        #'LPBH01': 'bebaeltertyp01',
                        #'LPBH02': 'bebaeltertyp02',
                        #'LPBH03': 'bebaeltertyp03',
                        #'LPBH04': 'bebaeltertyp04',
                        #'LPBH05': 'bebaeltertyp05',
                        #'LPBH06': 'bebaeltertyp06',
                        #'LPBH07': 'bebaeltertyp07',
                        #'LPBH08': 'bebaeltertyp08',
                        #'LPBH09': 'bebaeltertyp09',
                        #'LPBH10': 'bebaeltertyp10',
                       },
             'MLV00': {# Mehrplatzlagervorgänge
                       'LVVGNR': 'vorgangsnr',
                       'LVARTN': 'artnr',
                       'LVAUFA': 'auftragsart',
                       'LVAUFN': 'auftragsnr',
                       'LVAUPO': 'auftrags_position',
                       'LVBHTY': 'behaeltertyp',
                       'LVBPAE': 'benutzerprofil_aenderung',
                       'LVBPER': 'benutzerprofil_erfassung',
                       'LVBWSL': 'bewegungsschluessel',
                       'LVDFSL': 'dateifuehrungsschluessel',
                       'LVDTAE': 'aenderung_date',
                       'LVDTBE': 'bearbeitung_date',
                       'LVDTER': 'erfassung_date',
                       'LVDTLT': 'liefer_date',
                       'LVKDNR': 'kundennr',
                       'LVKOMP': 'komponentenartikel',
                       #'LVKZAR': 'KZ autom.Rueckmeldung',
                       #'LVKZAS': 'Auslagerungsstrategie',
                       #'LVKZEN': 'Einlagerungsstrategie',
                       'LVKZHK': 'herkunft',
                       'LVKZPR': 'prioritaet',
                       #'LVKZUM': 'KZ Umlagerung',
                       'LVKZVG': 'vorgangsart',
                       'LVLGPA': 'zielplatz',
                       'LVLGPL': 'quellplatz',
                       'LVMESL': 'mengeneinheit',
                       'LVMNGI': 'menge',
                       'LVMNGS': 'menge2',
                       #'LVPAN2': 'bez. Bestandssatz',
                       #'LVPANR': 'bez. Bestandssatz',
                       'LVSAN1': 'satznrALN00',
                       'LVSAN2': 'satznrALK00',
                       'LVSANR': 'satznr',
                       'LVSBAE': 'sachbearbeiter_aenderung',
                       'LVSBER': 'sachbearbeiter_erfassung',
                       'LVSBNR': 'sachbearbeiter_rueckmeldung',
                       #'LVSNLB': 'bez. Lagerbewegung 1',
                       'LVSTAT': 'satzstatus',
                       #'LVSTAV': 'KZ Status Vorgang',
                       #'LVSTNR': 'letzter StornoVG',
                       'LVX3VA': 'versandart',
                      },
             'ALK00': {# Lieferscheinköpfe
                       'LKSANK': 'satznr',
                       'LKSANB': 'bezogener_kopf',
                       'LKSBNR': 'sachbearbeiter',
                       'LKLGNR': 'lager',
                       'LKX3VA': 'versandart',
                       'LKKZTF': 'teilfakturiert',
                       'LKKDRG': 'rechnungsempfaenger',
                       'LKKDNR': 'warenempfaenger',
                       'LKLFSN': 'lieferscheinnr',
                       'LKDTLF': 'letzter_lieferschein_date',
                       'LKZTLF': 'letzter_lieferschein_time',
                       'LKDTST': 'lieferschein_storno_date',
                       'LKKZSL': 'sammellieferschein',
                       'LKKZLF': 'druckkennzeichen',
                       'LKKBNR': 'kommissionierbelegnr',
                       'LKDTKB': 'letzter_kommissionierbeleg_date',
                       'LKZTKB': 'letzter_kommissionierbeleg_time',
                       'LKLFDN': 'laufendenr',
                       'LKBELN': 'belegnr_freigabe',
                       # 'LKFGNR': 'Freigabenr AFA20
                       # 'LKFGSB': 'Sachbearb. Freigabe
                       'LKDTFG': 'freigabe_date',
                       'LKZTFG': 'freigabe_time',
                       'LKFGI1': 'freigabe_info1',
                       'LKFGI2': 'freigabe_info2',
                       #'LKFGLC': 'Anzahl Liefsch.'
                       'LKAUFS': 'auftragsnr',
                       'LKDTLT': 'liefer_date',
                       'LKKZ02': 'hrl_status',
                       'LKKZVA': 'alle_positionen_fakturiert',
                       'LKDTER': 'erfassung_date',
                       'LKZTER': 'erfassung_time',
                       'LKDTAE': 'aenderung_date',
                       'LKZTAE': 'aenderung_time',
                       'LKDFSL': 'dateifuehrungsschluessel',
                       'LKSTAT': 'satzstatus',
                      },
             'ALN00': {# Lieferscheinpositionen
                       'LNSANK': 'satznr_kopf',
                       'LNSANP': 'satznr',
                       # 'LNKANR': 'Übergeordnete Auftrags-Nr.
                       'LNAUFN': 'auftragsnr',
                       'LNAUPO': 'auftrags_position',
                       'LNARTN': 'artnr',
                       'LNKZKO': 'setartikel',
                       'LNBSTN': 'bestellnr',
                       'LNBSTP': 'bestellposition',
                       # 'LNVKE':  'verkaufseinheit', # ist immer leer
                       'LNLGNR': 'lager',
                       #'LNLGPL': 'lagerplatz', # ist immer leer
                       #'LNKZBE': 'Kz:keine Bestandsführung =1
                       'LNMNGO': 'menge_offen',
                       'LNDTLT': 'liefertermin_date',
                       'LNJWLT': 'liefertermin_woche',
                       'LNKZRK': 'rueckstand_erlaubt',
                       'LNKZZL': 'zuteilungskennzeichen',
                       'LNKZZU': 'bevorzugte_zuteilung',
                       'LNKDRG': 'rechnungsempfaenger',
                       'LNKDNR': 'kundennr',
                       'LNLFSN': 'lieferscheinnr',
                       'LNMNGL': 'menge',
                       'LNDTLF': 'lieferschein_date',
                       'LNZTLF': 'lieferschein_time',
                       #'LNKZVL': 'KZ. Vorab-Lieferschein
                       #'LNKZLD': 'Kz: Im LF. andrucken
                       #'LNKZL2': 'Kz: Im LF. andrucken
                       #'LNKZLF': 'Kz: LF-Schein drucken
                       #'LNKZFA': 'Kz:Pos.für Fakt.ausgewählt=
                       #'LNKZFF': 'Kz: Pos ist fakturierbar =
                       'LNDTST': 'storno_date',
                       'LNKZRE': 'lieferschein_ausloesung',
                       'LNKBNR': 'kommissionierbelegnr',
                       'LNMNGK': 'menge_komissionierbeleg',
                       'LNDTKB': 'komissionierbeleg_date',
                       'LNZTKB': 'komissionierbeleg_time',
                       'LNKZKB': 'komissionierbeleg_drucken',
                       'LNRGST': 'rechnungsstatus',
                       'LNDTVS': 'versand_date',
                       'LNSTOR': 'gutschrift',
                       'LNBELP': 'kommissionierbeleg_position',
                       #'LNFGNR': 'Freigabenr AFA20
                       #'LNFNFA': 'Fehlernr FG. AFA20
                       'LNLSTO': 'lieferscheinstorno',
                       'LNMNGF': 'menge_fakturierung',
                       'LNKZV2': 'voll_ausgeliefert',
                       #'LNPSTA': 'Packstatus
                       #'LNKZVS': 'Kz versandfertig
                       #'LNPROG': 'Herkunftsprogramm
                       #'LNKZUB': 'Übernahmekennzeichen
                       #'LNKINF': 'Kennzeicheninfo
                       #'LNAUPS': 'bezogene Position
                       'LNKZ03': 'hrl_status',
                       #'LNRSN1': 'Druck-Kz für KB
                       'LNDTER': 'erfassung_date',
                       'LNZTER': 'erfassung_time',
                       'LNDTAE': 'aenderung_date',
                       'LNZTAE': 'aenderung_time',
                       'LNDFSL': 'dateiführungsschluessel',
                       'LNSTAT': 'satzstatus',
                       'LNSBNR': 'sachbearbeiter_bearbeitung',
                      },
             'XKD00': {# Kundenadressen
                       'KDKDNR': 'kundennr',
                       'KDNAME': 'name1',
                       'KDNAM2': 'name2',
                       'KDNAM3': 'name3',
                       'KDNAM4': 'name4',
                       'KDSTR': 'strasse',
                       'KDPLZ': 'postleitzahl',
                       'KDORT': 'ort',
                       'KDLKZ': 'laenderkennzeichen',
                       'KDTELF': 'telefon',
                       'KDTFAX': 'fax',
                       'KDMOBI': 'mobil',
                       'KDPSTF': 'postfach', # gelegentlich genutzt
                       'KDPLZP': 'postfach_plz', # wenig genutzt
                       #'KDORTP': 'Ortsname (Postfach-PLZ)', # gelegentlich genutzt
                       #'KDPLZF': 'PLZ Firma', # sehr wenig genutzt
                       # 'KDGESF': 'Geschäftsführer', # wenig genutzt
                       'KDALSO': 'sortierfeld',
                       # 'KDSPSL': 'Sprache', # Werte 1 & 2
                       # 'KDWSL ': 'Währungs-Kennzeichen',
                       'KDKGRP': 'kundengruppe_id', # alphanum
                       'KDEMAL': 'email',
                       'KDHOME': 'url',
                       'KDSANR': 'adressdatei_id',
                       'KDDTER': 'erfassung_date',
                       'KDDTAE': 'aenderung_date',
                       },

             'XKS00': { # Kundenzusatzdaten
                       'KSKDNR': 'kundennr',
                       'KSLISP': 'liefersperre',
                       'KSAWRT': 'offener_aftragswert',
                       'KSAKWR': 'kreditlimit',
                       'KSCOMP': 'company',
                       'KSIAKZ': 'inland_ausland',
                       'KSFNRK': 'interne_firmennr',
                       'KSINFL': 'unsere_lieferantennumemr',
                       'KCUSTN': 'ustid',
                       'KSLIMI': 'kreditlimit2',
                       'KSSKSL': 'skontoschluessel',
                       'KSDKSL': 'delcredereschlüssel',
                       'KSMASP': 'mahnsperre',
                       'KSKDZA': 'lastschrift',
                       'KSBOKZ': 'bonnitaet',
                       # 'KSKLTA': 'Kd/Li-Texte anzeigen       ',
                       # 'KSINF1': 'Inf. 1                     ',
                       'KCVERB': 'verband',
                       #'KSKRED': 'Verbands-/Mischkto-Satz    ',
                       'KCMGVB': 'mitgliednr',
                       #'KCBBN':  'Bundeseinheitl.Betriebsnr. ',
                       #'KCBBS':  'Bundeseinh.Betriebsstell.Nr',
                       #'KCVRKZ': 'Kz. "Rechnungsliste erst." ',
                       #'KCRGKZ': 'Kz. "Rechnung drucken"     ',
                       #'KCKOIN': 'Kontoinhaber               ',
                       #'KCHSTU': 'Auswertungsebene / KD-Hier ',
                       #'KCSKRL': 'Skto-Ausweis RGL Verband ',
                       #'KCEDIL': 'LS-Daten per EDI         ',
                       #'KCPRIA': 'Inlands-/Auslandspreise  ',
                       'KCE2IL': 'ILN',
                       },
             'AKZ00': {# Kundenstamm für Auftragsverwaltung
                       'KZKDNR': 'Kunden-nr              ',
                       #'KZSBNR': 'zuständiger Sachbearbeiter ',
                       'KZVRT': 'vertreter',
                       'KZGEB': 'gebiet',
                       'KZBRAN': 'branche',
                       'KZDSTK': 'distrikt',
                       #'KZKZVB':' Kz. 'Kunde ist Verbraucher','
                       #'KZKZZU': 'Bevorzugte Zuteilung       ',
                       #'KZKZRK': 'Rückstand möglich          ',
                       'KZX3LB': 'lieferbedingung',
                       'KZX3VP': 'verpackungsvorschrift',
                       'KZX3VS': 'versandart',
                       #'KZVANR': 'Versand-Adress Nr.         ',
                       #'KZEXPR': 'Expreßgut-Station          ',
                       'KZLGNR': 'auslieferunglager',
                       #'KZX3ZB': 'Zahl.-Bed-Schl.            ',
                       #'KZKDRG': 'Rechnungs-Zahler           ',
                       #'KZWSL ': 'Währungs-Kennzeichen       ',
                       #'KZKZBO': 'Bonus-Kennzeichen          ',
                       #'KZKZSL': 'Sammellieferschein         ',
                       #'KZKZRV': 'Rechnung nur vollständig   ',
                       #'KZKZSR': 'Sammelrechnung             ',
                       #'KZKZAB': 'Steuerung AB-Andruck       ',
                       #'KZABCO': 'Formular-Anz./Auftragsbest.',
                       #'KZKBCO': 'Formularanz./ Komm.-Beleg  ',
                       #'KZLSCO': 'Formularanz./ Lieferschein ',
                       #'KZRGCO': 'Formularanz./ Rechnung     ',
                       #'KZTELF': 'telefon',
                       #'KZTFAX': 'fax',
                       'KZINFO': 'sachbearbeiter',
                       'KZDTAE': 'updated_at',
             },
             'XAD00': {# Abweichende Lieferadressen
                       'ADNAME': 'name1',
                       'ADNAM2': 'name2',
                       'ADNAM3': 'name3',
                       'ADNAM4': 'name4',
                       'ADSTR': 'strasse',
                       'ADPLZ': 'postleitzahl',
                       'ADORT': 'ortsname',
                       'ADLKZ': 'laenderkennzeichen',
                       'ADORTT': 'ortsteil',
                       'ADKZAD': 'adressaufbereitung',
                      },
             'AAT00': {# Auftragsnr
                       'ATAUFN': 'auftragsnr',
                       'ATAUPO': 'auftragsposition',
                       'ATTART': 'textart',
                       'ATLFNR': 'nr',
                       'ATTX60': 'text',
                       'ATKZAB': 'andruck_ab',
                       'ATKZLF': 'andruck_ls',
                       'ATKZRG': 'andruck_re',
                      },
             'ISA00': {# MyPL Schnittstelle: Komissionierbeleg
                       'IAFNR': 'firma',
                       'IALGNR': 'lagernr',
                       'IAKBNR': 'kommissionierbelegnr',
                       'IAAUFN': 'auftragsnr',
                       'IADATE': 'anforderung_date',
                       'IATIME': 'anforderung_time',
                       'IADFSL': 'dateifuehrungsschluessel',
                       'IASTAT': 'status',
                       'IASANR': 'satznr',
                      },
             'ISK00': {# MyPL Schnittstelle: Warenzugang aus Umlagerung
                       'IKFNR': 'firma',
                       'IKKBNR': 'kommissionierbelegnr',
                       'IKKPOS': 'kommissionierbelegposition',
                       'IKAUFN': 'auftragsnr',
                       'IKAUPO': 'auftragsposition',
                       'IKRMNG': 'rueckmeldemenge',
                       'IKDATE': 'rueckmeldung_date',
                       'IKTIME': 'rueckmeldung_time',
                       'IKDFSL': 'dateifuehrungsschluessel',
                       'IKSTAT': 'status',
                       'IKSANR': 'satznr',
                      },
             'ISR00': {# MyPL Schnittstelle: KB-Rückmeldung
                       'IRFNR': 'firma',
                       'IRKBNR': 'kommissionierbelegnr',
                       'IRKPOS': 'kommissionierbelegposition',
                       'IRAUFN': 'auftragsnr',
                       'IRAUPO': 'auftragsposition',
                       'IRMENG': 'rueckmeldemenge',
                       'IRKZNU': 'kennzeichen_nullen',
                       'IRKZST': 'kennzeichen_stornieren',
                       'IRFCOD': 'letzter_fehlercode',
                       'IRDFSL': 'dateifuehrungsschluessel',
                       'IRSTAT': 'status',
                      },
             'ISB00': {# MyPL Schnittstelle: Lagerbuchungsschnittstelle
                       'IBFNR': 'firma',
                       'IBBWSL': 'bewegungsschluessel',
                       'IBLGNR': 'lager',
                       'IBARTN': 'artnr',
                       'IBMNGB': 'menge',
                       'IBINFO': 'info',
                       'IBFCOD': 'letzter_fehlercode',
                       'IBDFSL': 'dateifuehrungsschluessel',
                       'IBSTAT': 'status',
                      },
             'ISZ00': {# MyPL Schnittstelle: Warenzugang aus Auftrag
                       'IZFNR ': 'firma',
                       'IZBSTN': 'bestellnr',
                       'IZWVNR': 'warenvereinnahmungsnr',
                       'IZDTWZ': 'zugang_date',
                       'IZTIME': 'zugang_time',
                       'IZDFSL': 'dateiführungsschlüssel',
                       'IZSTAT': 'status',
                       'IZSANR': 'satznr',
                       },
             'XAR00': {# Artikelstamm
                        'ARARTN': 'artnr',
                        'ARSTAT': 'status',
                        'ARARTH': 'artikelhauptgruppe',
                        'ARARTG': 'artikelgruppe',
                        'ARBEZ1': 'ARBEZ1',
                        'ARBEZ2': 'ARBEZ2',
                        'ARBEZ3': 'ARBEZ3',
                        'ARGEWI': 'gewicht',
                        'ARNGEW': 'gewicht_netto',
                        'AREAN': 'ean',
                        'ARMEBE': 'mengeneinheit',
                        'ARZOGR': 'zollgruppe',
                        'ARZTNR': 'statistischewarennr',
                        'ARPREV': 'listenpreis',
                        'ARMALG': 'laenge',
                        'ARMABR': 'breite',
                        'ARMATI': 'tiefe',
                        'AREART': 'ersatzartikel',
                        'ARMCOD': 'matchcode',
                        #'ARMEBE': 'Mengeneinheit/Bestandsf.',
                        #'ARMEER': 'Mengeneinheit/Erfassung',
                        #'ARFAKT': 'Umrechn.-Faktor  ER-->BE',
                        #'ARMEPR': 'Mengeneinheit/Preis',
                        #'ARFAPR': 'Umrechn.-Faktor  PR-->BE',
                        'ARABC': 'abc1',
                        'ARABC2': 'abc2',
                        'ARABC3': 'abc3',
                        #'ARZOGR': 'Zoll-Grupppe-nr',
                        'ARZTNR': 'zolltarifnr',
                        'ARURLD': 'ursprungsland',
                        #'ARPREV': 'Verkaufspreis',
                        #'ARPRE2': 'Verkaufspreis 2',
                        #'ARPREA': 'Verkaufspreis Ausland',
                        #'ARPRI2': 'Vk-Preis/Inland - neu -',
                        #'ARPRA2': 'Vk-Preis/Ausland - neu -',
                        #'ARDTPI': 'Ab Datum Vk/Inland - neu -',
                        #'ARDTPA': 'Ab Datum Vk/Ausland - neu -',
                        #'ARPGSZ': 'Preisgruppen-Staffel-Zuordn',
                        #'ARWSL' : 'Währungs-Kennzeichen',
                        #'ARRBPR': 'Artikel-Rabatt-%-Satz',
                        #'ARKZKW': 'Ohne wertmäßige Best.-Führ.',
                        'ARKZKO': 'setartikel',
                        'ARKZVK': 'verkaufsteil',
                        #'ARKZNE': 'Kennzeichen Neuheit',
                        #'ARDTNA': 'Auslieferungs-Datum/Neuheit',
                        'ARKZNA': 'auslaufartikel',
                        'ARKZAT': 'artikeltexte_vorhanden',
                        'ARVKUB': 'volumen',
                        'ARKZZS': 'zuteilungssperre',
                        'ARINFO': 'info',
                        'ARMGMA': 'mindestabnahmemenge',
                        'ARCTAR': 'ersatzteil',
                        'ARKZVP': 'ist_verpackung',
                        #'ARKZWB': 'webshop',
                        #'ARHAFO': 'handelsform',
                        #'ARDAFO': 'darreichungsform',
                        #'ARKZRG': 'andruck_in_rechnung',
                        'ARSBER': 'Sachb. Erfassung',
                        'ARBPER': 'BenutzerPr.Erfassung',
                        'ARSBAE': 'Sachb.letzte Änderung',
                        'ARBPAE': 'BenutzerPr.letzte Änderung',
                        'ARDTER': 'erfassung_date',
                        'ARDTAE': 'aenderung_date', },
             'ASK00': {# Set/Komponenten
                        # 'SKFNR':  'firma',
                        'SKARTN': 'artnr',
                        # 'SKAUFN': 'Auftrags-nr',
                        # 'SKAUPO': 'Auftrags-Position',
                        'SKLFNR': 'laufende_nr',
                        'SKKART': 'komponenten_artnr',
                        'SKMENG': 'menge_im_set',
                        # 'SKKZSE': 'KENNZ: SERIEN-NR.-ARTIKEL',
                        # 'SKKZ01': 'AbwStddSet',
                        # 'SKKZ02': 'Kz. ohne Bestandsf.',
                        # 'SKKZ03': 'Auf/Ang',
                        # 'SKPROZ': 'Anteil am Umsatz in %',
                        # 'SKKZPD': 'Kz PrFnd',
                        # 'SKHPTP': 'NatRbPos',
                        # 'SKDTAE': 'updated_at_date',
                        # 'SKZTAE': 'updated_at_time',
                        },
             'AAK00': {# Auftragsköpfe
                       # 'AKFNR ': 'Firma                       ',
                       'AKAUFN': 'auftragsnr',
                       'AKSBNR': 'sachbearbeiter',
                       # 'AKABT ': 'Abteilungs-nr           ',
                       # 'AKAGRP': 'Abteilungs-Gruppe/Sparte    ',
                       # 'AKFGRP': 'Firmen-Gruppe               ',
                       'AKAUFA': 'art',
                       # 'AKRANR': 'Rahmenvereinbarungs-Nr.     ',
                       # 'AKKANR': 'Übergeordneter Auftrag      ',
                       # 'AKFNRM': 'Mandanten-nr            ',
                       # 'AKKDNR': 'Kunden-nr/Warenempfänge ',
                       # 'AKKDN3': 'Kunden-Nr/Verbraucher       ',
                       # 'AKEGCD': 'Ländercode / EG             ',
                       # 'AKUSTN': 'USt-Id-nr               ',
                       # 'AKVANR': 'Versandadress-Nr.           ',
                       # 'AKALS1': 'Alphasortierung/Warenempfän ',
                       # 'AKKDRG': 'Kundennr.Rechnungs-Empfänge ',
                       # 'AKALS2': 'Alphasortierung/Rech-Empfän ',
                       # 'AKVERB': 'Verband/Mischkonto          ',
                       # 'AKABEM': 'Ab-Empfänger: R = Rg-Zahler ',
                       # 'AKRGEM': 'Rechnungsempfänger          ',
                       'AKNRKD': 'auftragsnr_kunde',
                       'AKDTKD': 'auftragsdatum_kunde',
                       # 'AKDTLE': 'Leih-Datum                  ',
                       'AKDTKW': 'kundenwunsch_date',
                       # 'AKJWKW': 'Kundenwunschtermin CJJWW    ',
                       # 'AKPROB': 'Objekt/Projekt/Aktion       ',
                       # 'AKDTVA': 'Valuta-Datum/Erfassung      ',
                       # 'AKVALT': 'Abstandstage Valuta         ',
                       'AKDTLT': 'liefer_date',
                       'AKIK01': 'fixtermin',
                       # 'AKJWLT': 'Liefertermin CJJWW          ',
                       # 'AKX3ZB': 'Zahlungsbedingungs-Schlüsse ',
                       # 'AKX3VA': 'Versandarten-Schlüssel      ',
                       # 'AKX3LB': 'Lieferbedingungs-Schlüssel  ',
                       # 'AKVPKE': 'Verpackungskosten           ',
                       # 'AKVSKE': 'Versandkosten               ',
                       # 'AKNBKE': 'Nebenkosten                 ',
                       # 'AKX4NB': 'Textschl. Nebenkosten       ',
                       # 'AKNBT1': 'Zus. Nebenkosten 1          ',
                       # 'AKNTY1': 'Typ/Zus. Nebenkosten 1      ',
                       # 'AKX4N1': 'Textschl. zus. Nebenkosten  ',
                       # 'AKNBT2': 'Zus. Nebenkosten 2          ',
                       # 'AKNTY2': 'Typ/Zus. Nebenkosten 2      ',
                       # 'AKX4N2': 'Textschl. zus. Nebenkosten  ',
                       # 'AKRBP1': 'Auftrags-Rabatt-%-1         ',
                       # 'AKRBP2': 'Auftrags-Rabatt-%-2         ',
                       # 'AKX3R1': 'Textschl. Rabatt 1          ',
                       # 'AKX3R2': 'Textschl. Rabatt 2          ',
                       # 'AKKZRX': 'Kz.Rabatt Brutto            ',
                       # 'AKMWKZ': 'Umsatz-Steuerprofil         ',
                       # 'AKWSL ': 'Währungs-Kennzeichen        ',
                       # 'AKKURS': 'Wechsel-Kurs                ',
                       # 'AKKUFA': 'Kursfaktor                  ',
                       # 'AKSPSL': 'Sprache                     ',
                       # 'AKVRT1': 'Vertreter 1                 ',
                       # 'AKVRT2': 'Vertreter 2                 ',
                       # 'AKPRZA': 'Aufteilungs-%-Satz          ',
                       # 'AKBZRG': 'Bezogene RG-nr          ',
                       # 'AKLGN1': 'Auslieferungslager          ',
                       # 'AKLGN2': 'Zugangslager                ',
                       # 'AKTRNR': 'Touren-nr               ',
                       # 'AKLINR': 'Lieferant bei Strecke       ',
                       # 'AKSPED': 'Spediteur                   ',
                       # 'AKKZBE': 'Steuerung Best.-Druck       ',
                       # 'AKKZST': 'Kennzeichen Streckengeschäf ',
                       # 'AKKZWS': 'WZ/RE-Sperre                ',
                       # 'AKKZIN': 'Kennzeichen interner Beleg  ',
                       # 'AKKZBO': 'Steuerung Bonus-Abrechnung  ',
                       'AKKZTF': 'teillieferung', # bzw. Teilfakturierung
                       # 'AKKZSR': 'Kz.Drucken in Sammelrech=1  ',
                       # 'AKKZZF': 'un-/versteuert              ',
                       'AKKZVA': 'voll_ausgeliefert',
                       # 'AKKZZU': 'Kz.Bevorzugte Zuteilung     ',
                       # 'AKKZRK': 'Kz: Rückstand möglich       ',
                       # 'AKKZSL': 'Kz.Sammel-Lieferschein      ',
                       # 'AKKZNN': 'Kz.Nachnahme                ',
                       # 'AKKZAR': 'Kz.Leihart                  ',
                       # 'AKABTP': 'Abt. für Prüfung KD-Zusatz  ',
                       # 'AKDTER': 'Datum Erfassung CJJMMTT     ',
                       # 'AKZTER': 'Uhrzeit der Erfassung       ',
                       # 'AKDTAE': 'Datum l. Änderung CJJMMTT   ',
                       # 'AKZTAE': 'Uhrzeit letzte Änderung     ',
                       # 'AKDTAB': 'Datum letzte Auftragsbestät ',
                       # 'AKDTLF': 'Datum letzter Lieferschein  ',
                       # 'AKDTKB': 'Datum ltzt.Kommissionierbel ',
                       # 'AKDTFA': 'Datum letzte Rechnung/Gutsc ',
                       # 'AKKZAE': 'AB: nur geänderte Posit.    ',
                       # 'AKFKZA': 'Formular-KZ AB              ',
                       # 'AKFKZK': 'Formular-KZ Kommission.Bele ',
                       # 'AKFKZL': 'Formular-KZ Lieferschein    ',
                       # 'AKFKZR': 'Formular-KZ Rechnung/Gutsch ',
                       # 'AKSFAA': 'AB Sofort                   ',
                       'AKSFAL': 'LF Sofort',
                       'AKSFAK': 'Komm.-Beleg sofort',
                       # 'AKSFAR': 'RG Sofort                   ',
                       # 'AKABCO': 'Anzahl AB                   ',
                       'AKKBCO': 'anzahl_kommissionierbelege',
                       'AKLSCO': 'anzahl_liefscheine',
                       # 'AKRGCO': 'Anzahl Rechnungen           ',
                       # 'AKOQZO': 'Outqueue-Zuordnung          ',
                       # 'AKGEB ': 'Gebiet                      ',
                       # 'AKBRAN': 'Branche                     ',
                       # 'AKPLZ':  'plz',
                       'AKLKZ': 'land',
                       # 'AKVRG1': 'Vertriebs-Gruppe 1          ',
                       # 'AKVRG2': 'Vertriebs-Gruppe 2          ',
                       # 'AKDSTK': 'Distrikt                    ',
                       # 'AKAWRT': 'Auftragswert                ',
                       # 'AKSTOR': 'Kennzeichen Stornierung     ',
                       # 'AKFORM': 'Rechnungsart                ',
                       # 'AKMJBU': 'Buchungsmonat               ',
                       # 'AKKZWR': 'Kz wertmäßig                ',
                       # 'AKKZVS': 'Vertriebsstatus             ',
                       # 'AKFA1A': 'Preisstufe                  ',
                       # 'AKFA2A': 'Fax-Zustellung              ',
                       # 'AKFA4A': 'Herkunft                    ',
                       # 'AKKZRE': 'Retouren-Beleg ja/nein      ',
                       # 'AKKZSH': 'Hrst Strecke                ',
                       # 'AKDTRV': 'Rahmen: gültig ab           ',
                       # 'AKDTRB': 'Rahmen: gültig bis          ',
                       # 'AKKDN1': 'Adresse 1                   ',
                       # 'AKKDN2': 'Adresse 2                   ',
                       # 'AKZUOR': 'Zuordnung für dezentrale An ',
                       # 'AKDFSL': 'Dateiführungs-Schlüssel     ',
                       # 'AKSTAT': 'satzstatus'
                      },
            'AAP00': { # Auftragspositionen
                       # 'APFNR ': 'Firma                       ',
                       # 'APAUFN': 'Auftrags-nr             ',
                       'APAUPO': 'position',
                       'APSBNR': 'sachbearbeiter',
                       # 'APABT':  'Abteilungs-nr           ',
                       # 'APAGRP': 'Abteilungs-Gruppe/Sparte    ',
                       # 'APFGRP': 'Firmen-Gruppe               ',
                       # 'APFNRX': 'Best.-Führungsfirma         ',
                       # 'APKDNR': 'Kunden-nr               ',
                       # 'APKDRG': 'Kundennr.Rechnungs-Empfänge ',
                       # 'APVERB': 'Verband/Mischkonto          ',
                       # 'APLINR': 'Lieferanten-nr          ',
                       # 'APAUFA': 'AUFTRAGS-ART                ',
                       # 'APHPTP': 'zugeordnete_position',
                       # 'APRANR': 'rahmenauftrag',
                       # 'APRAPO': 'rahmenposition',
                       # 'APKANR': 'Übergeordneter Auftrag',
                       # 'APANNR': 'Angebots-nr             ',
                       # 'APANPO': 'Angebots-Positions-nr   ',
                       # 'APBSTN': 'Bestell-nr              ',
                       # 'APBSTP': 'Bestell-Position            ',
                       # 'APLHNR': 'LH-Nr.                      ',
                       # 'APLHPO': 'Leihauftrags-Pos            ',
                       'APVGNR': 'vorgangs_nr',
                       'APVGPO': 'vorgangs_position',
                       # 'APFAUN': 'Fertigungsauftrag           ',
                       # 'APPROB': 'Objekt/Projekt/Aktion       ',
                       'APARTN': 'artnr',
                       # 'APARTG': 'Artikel-Gruppe              ',
                       # 'APARTH': 'Artikel-Haupt-Gruppe        ',
                       # 'APKZSO': 'Kennzeichen Sonderartikel   ',
                       'APLGNR': 'lager',
                       # 'APLGRP': 'Lagergruppe                 ',
                       # 'APLGPL': 'Lager-Platz                 ',
                       # 'APKZBE': 'Ohne Bestandsführung        ',
                       # 'APKZSE': 'Serien-/Chargenartikel      ',
                       'APKZKO': 'komponentenaufloesung',
                       'APKZPS': 'Positionsbezogener Set',
                       # 'APKZEP': 'KZ: Eigen-Produkt           ',
                       # 'APKZMU': 'Muster-Artikel              ',
                       'APMNG': 'bestellmenge',               # Die Menge, die der Kunde haben will
                       'APMNGL': 'Menge zu liefern',
                       'APMNGG': 'Menge/Liefersch.nichtfakt',
                       'APMNGF': 'Fakturierte Menge',          # Menge, die geliefert und fakturiert ist
                       'APMNGR': 'Menge AFA35',
                       'APMNGB': 'Bestellmenge in ME XLF',
                       'APMESL': 'Mengen-Einheit',
                       'APMEKZ': 'ME XLF/AAP',
                       # 'APDEZI': 'Anzahl Dezimalstellen       ',
                       # 'APVOLM': 'Inhalt VKE/Gebinde          ',
                       # 'APGANZ': 'Bestellte Gebinde           ',
                       # 'APGANF': 'Fakturierte Gebinde         ',
                       # 'APGANG': 'Gebinde/Lief.nicht fakt     ',
                       # 'APGANL': 'Gebinde/zu liefern          ',
                       # 'APGANP': 'Gebinde verpackt            ',
                       # 'APGANR': 'Gebinde AFA35               ',
                       # 'APGEWI': 'Gewicht                     ',
                       'APPREV': 'Verkaufs-Preis',
                       # 'APPEBN': 'Ebene Preisfindung          ',
                       # 'APKZPR': 'Preiskennzeichen Verkauf    ',
                       # 'APMEPR': 'Preis-Einheit               ',
                       # 'APFAPR': 'Faktor APMEH --> APMEPR     ',
                       'APFWRT': 'fakturierter Wert',
                       'APOWRT': 'offener Auftragswert',
                       'APPREL': 'Listen-Preis',
                       # 'APPREE': 'Einstands-Preis             ',
                       # 'APPRKZ': 'Preiskennzeichen Lager      ',
                       # 'APWSLE': 'Währungsschlüssel: EK       ',
                       # 'APKURS': 'Wechselkurs EK              ',
                       # 'APKUFA': 'Kursfaktor/EK               ',
                       # 'APRBP1': 'Pos-Rabatt-1                ',
                       # 'APRBP2': 'Pos-Rabatt-2                ',
                       # 'APRBP3': 'Pos-Rabatt-3                ',
                       # 'APRBP4': 'Pos-Rabatt-4                ',
                       # 'APKZR1': 'Berechnung Rabatt 1         ',
                       # 'APKZR2': 'Berechnung Rabatt 2         ',
                       # 'APKZR3': 'Berechnung Rabatt 3         ',
                       # 'APKZR4': 'Berechnung Rabatt 4         ',
                       # 'APX3R1': 'Textschl. Rabatt 1          ',
                       # 'APX3R2': 'Textschl. Rabatt 2          ',
                       # 'APX3R3': 'Textschl. Rabatt 3          ',
                       # 'APX3R4': 'Textschl. Rabatt 4          ',
                       # 'APKZRU': 'Kz.Rabatt versteckt         ',
                       # 'APKZRX': 'Kz.Rabatte Brutto           ',
                       # 'APKZRB': 'Kz: kein Auftragsrabatt = 1 ',
                       # 'APKZET': 'Steuerung Sortiments-Rabatt ',
                       # 'APKZSR': 'Sortiments-Rabatt gewährt   ',
                       # 'APMWAR': 'Steuerart / Artikel         ',
                       'APDTLT': 'liefer_date',
                       # 'APJWLT': 'Liefertermin CJJWW          ',
                       'APDTKD': 'kundenwunsch_date',
                       # 'APJWKD': 'Kundenwunschtermin CJJWW    ',
                       'APDTLN': 'neuliefer_date',
                       # 'APJWLN': 'Liefertermin neu CJJWW      ',
                       # 'APKZTE': 'Kz: Termin-Format: 1 =WW/JJ ',
                       # 'APKZAB': 'Position in AB gedruckt     ',
                       'APKZAE': 'geaendert',
                       # 'APKZST': 'Kennzeichen Streckengeschäf ',
                       # 'APKZFA': 'Rg-Freigabe                 ',
                       # 'APKZEK': 'Schnittstelle Einkauf       ',
                       # 'APKZBD': 'Steuerung Best.-Druck       ',
                       # 'APKZSP': 'KZ: Sperre für Übernahme    ',
                       # 'APHERK': 'Herkunft                    ',
                       # 'APKZSS': 'Kz Stapelschnittstelle',
                       # 'APFA1A': 'Lieferschein-Auslösung      ',
                       # 'APKZLA': 'Lieferschein-Auslösung 2    ',
                       # 'APLFKZ': 'Kz. Lfsch drucken           ',
                       'APKZZL': 'zuteilungskennzeichen',
                       'APKZFG': 'KB/LS-Feigabe',
                       'APKZRE': 'Lieferschein -Auslösung',
                       # 'APKZZU': 'Kz.Bevorzugte Zuteilung     ',
                       'APKZLF': 'Kz:Im LfSchein andrucken',
                       # 'APKZVL': 'Vorab-Lieferschein          ',
                       # 'APKZRD': 'Kz:Pos in Rech.nicht andr.= ',
                       # 'APKZSF': 'Kz: In Sofort-Form andrucke ',
                       # 'APKZSV': 'Zusätzliches Sofortformular ',
                       # 'APKZSA': 'Kz: keine AE-Statistik = 1  ',
                       # 'APKZSM': 'Kz:keine Mengen-Statistik=1 ',
                       # 'APKZSU': 'Kz:keine Umsatzstatistik=1  ',
                       # 'APKZBA': 'Kz: kein Auftragsbestand=1  ',
                       # 'APKZRK': 'Kz: Rückstand erlaubt = 1   ',
                       'APKZVA': 'voll_ausgeliefert',
                       # 'APKZAF': 'Kz:Abruf aus Rahmenauftrag  ',
                       # 'APKZRA': 'Kz:Rahmen-Pos               ',
                       # 'APKZPA': 'Kz:Preisänderung = 1        ',
                       'APKZTA': 'Kz:Terminänderung = 1       ',
                       'APKZMA': 'Kz:Mengenänderung = 1       ',
                       # 'APPRVK': 'Provisions-Kennzeichen      ',
                       # 'APPWRT': 'Provisionswert              ',
                       # 'APPRV1': 'Provisions-%-Satz 1         ',
                       # 'APPRV2': 'Provisions-%-Satz 2         ',
                       # 'APGATG': 'Garantie-Tage               ',
                       # 'APX4TR': 'Transaktions-Code           ',
                       # 'APKZBO': 'Kz Bonus                    ',
                       # 'APKZEE': 'Einstandspreis eingebbar    ',
                       # 'APKTO ': 'Erlöskonto                  ',
                       # 'APKTOK': 'Kosten-Konto                ',
                       # 'APKST ': 'Kostenstelle                ',
                       # 'APKTR ': 'Kostenträger                ',
                       # 'APZUOR': 'Zuordnung für dezentrale An ',
                       # 'APRES1': 'Firma/Herkunft              ',
                       # 'APFA3A': 'Bestell-Zusammenfass./Dispo ',
                       'APFA4A': 'Teil-Zuteilungs-Verbot',
                       # 'APKZBF': 'ZUSATZANGABE RAHMEN/ABRUF   ',
                       # 'APDRKZ': 'Preisdruck                  ',
                       # 'APHLKZ': 'Kz Hochregal                ',
                       # 'APHLCR': 'Chargenrein                 ',
                       # 'APPGSZ': 'Preisstufe                  ',
                       # 'APUAPR': 'Typ Preisfaktor             ',
                       # 'APMEGB': 'Mengeneinheiten-Schlüssel   ',
                       # 'APSFRG': 'Pos für SofortRg ausgewählt ',
                       # 'APKZDI': 'Beschaffungsschlüssel       ',
                       # 'APKZVS': 'Vertriebsstatus             ',
                       # 'APDTRV': 'Rahmen: gültig ab           ',
                       # 'APDTRB': 'Rahmen: gültig bis          ',
                       # 'APAUPS': 'bezogene Position           ',
                       # 'APSNPF': 'StzNr Preisfindung          ',
                       'APMG01': 'Menge 1',
                       # 'APWR01': 'Preis 1                     ',
                       # 'APPR01': '%-Satz 1                    ',
                       'APDTZU': 'Datum Zuteilung',
                       'APZTZU': 'Uhrzeit Zuteilung HHMMSS',
                       'APJNZU': 'Jobnr Zuteilung',
                       # 'APDTER': 'Datum Format CJJMMTT        ',
                       # 'APZTER': 'Uhrzeit der Erfassung       ',
                       # 'APDTAE': 'Datum Format CJJMMTT        ',
                       # 'APZTAE': 'Uhrzeit letzte Änderung     ',
                       # 'APSBAE': 'Sachb.letzte Änderung       ',
                       # 'APDFSL': 'Dateiführungs-Schlüssel     ',
                       # 'APSTAT': 'Satzstatus                  ',
                      },
             'IET00': { # Etikettendruckdatei
                       'ETSANR': 'satznr',
                       'ETARTN': 'artnr',
                       'ETBEZ1': 'bezeichnung1',
                       'ETBEZ2': 'bezeichnung2',
                       'ETLGPA': 'lagerplatzAn',
                       'ETDTBE': 'datumBearbeitung',
                       'ETMNGI': 'vorgangsMenge',
                       #'ETBSTN': 'Bestellummer',
                       #'ETBSTP': 'Bestellposition',
                       #'ETAUFN': 'KdAuftrag',
                       #'ETAUPO': 'KdAuftragspos',
                       # 'ETKZVG': 'vorgangskennz',
                       # 'ETKZHK': 'vorgangsherkunft',
                       # 'ETETNR': 'EtikettenNr',
                       #'ETANZ':  'Anzahl Etiketten',
                       'ETDRET': 'druck',
                       #'ETRA30': 'Reserve-Feld A 30',
                       #'ETR1A1': 'Reserve-Feld 1 A 1',
                       #'ETR2A1': 'Reserve-Feld 2 A 1',
                       #'ETR3A1': 'Reserve-Feld 3 A 1',
                       #'ETR4A1': 'Reserve-Feld 4 A 1',
                       #'ETR5A1': 'Reserve-Feld 5 A 1',
                       #'ETRDT1': 'Reserve-Datum 1',
                       #'ETRDT2': 'Reserve-Datum 2',
                       #'ETRDT3': 'Reserve-Datum 3',
                       #'ETRMG1': 'Reserve-Menge 1',
                       #'ETRMG2': 'Reserve-Menge 2',
                       #'ETRMG3': 'Reserve-Menge 3',
                       #'ETRMG4': 'Reserve-Menge 4',
                       #'ETRMG5': 'Reserve-Menge 5',
                       'ETDTER': 'erfassung_date',
                       'ETSBER': 'sachbearbeiter_erfassung',
                       'ETDTAE': 'aenderung_date',
                       'ETSBAE': 'sachbearbeiter_aenderung',
                       'ETDFSL': 'dateifuehrungsschluessel',
                       'ETSTAT': 'satzstatus',
                       },
             'BED00': { # Datei fuer die Zentrale-Meldung innerg. Warenverk.
                       'EDFNR ': 'firmennr',
                       'EDPKTO': 'personenkonto',
                       'EDBEKZ': 'berichtigungskennzeichen',
                       # 'EDJHBU': '???',
                       'EDJJBU': 'buchungsjahr',
                       'EDQUAR': 'meldequartal',
                       'EDEGCF': 'egcd_fremde_firma',
                       'EDUSTF': 'ustnr_fremde_firma',
                       'EDEGCE': 'egcd_eigene_firma',
                       'EDUSTE': 'ustnr_eigene_firma',
                       'EDBEMG': 'bemessgrundlage',
                       'EDKZ  ': 'warenbewegungskennzeichen',
                       'EDKZDR': 'kennzeichen_dreiecksgeschaeft',
                       'EDRAFF': 'geraffte_daten',
                       'EDA01A': 'buchhaltungskennzeichen',
                       # 'EDA01B': 'reserve_b',
                       # 'EDA01C': 'reserve_c',
                       # 'EDA10A': 'reserve_d',
                       # 'EDA10B': 'reserve_e',
                       # 'EDRBT ': 'reserve_betrag',
                       'EDSTBT': 'steuerbetrag',
                       # 'EDR1BT': 'reserverbetrag_1',
                       # 'EDR2BT': 'reserverbetrag_2',
                       # 'EDR3BT': 'reserverbetrag_3',
                       # 'EDR4BT': 'reserverbetrag_4',
                       # 'EDR5BT': 'reserverbetrag_5',
                       # 'EDR6BT': 'reserverbetrag_6',
                       },
             'XED00': { # Intrastat-Meldungs-Datei
                         'EDINKZ': 'kennziffer',
                         'EDFORM': 'anmeldeform',
                         'EDSITZ': 'sitz_versender_empfaenger',
                         'EDMONA': 'anmeldemonat',
                         'EDFIL1': 'fueller01',
                         'EDPOS ': 'paginiernr',
                         'EDFIL2': 'fueller02',
                         'EDBLFA': 'bundesland_finanzamt',
                         'EDSTNR': 'steuernr',
                         'EDUSNR': 'unterscheidungsnr',
                         'EDLCOD': 'bestimmungsland',
                         'EDBLND': 'ursprungsbundesland',
                         'EDGSCH': 'art_des_geschaefts',
                         'EDVKZW': 'verkehrszweig',
                         'EDFIL3': 'fueller03',
                         'EDPORT': 'hafen_flughafen',
                         'EDFIL4': 'fueller04',
                         'EDSTWN': 'statistische_warennr',
                         'EDFIL5': 'fueller05',
                         'EDFIL6': 'fueller06',
                         'EDVERF': 'statistisches_verfahren',
                         'EDGEWI': 'einganmasse_in_kg',
                         'EDMNGX': 'besondere_masseinheit',
                         'EDFIL7': 'fueller07',
                         'EDWRWA': 'warenwert_netto',
                         'EDWRGU': 'statistischer_wert',
                         'EDFIL8': 'fueller08',
                         'EDBUMM': 'bezugsmonat',
                         'EDBUJJ': 'bezugsjahr',
                         'EDKREI': 'mineraloelerhebungspreis',
                         'EDFIL9': 'fueller09',
                       },
             'XCK00': { # Ablaufkontrolle
                       'CKJNUM': 'jobnr',
                       'CKBLNA': 'blockname',
                       'CKJNAM': 'jobname',
                       'CKUSER': 'benutzer',
                       'CKWSID': 'bildschirmidentifikation',
                       'CKFNR ': 'firmennr',
                       'CKFCOD': 'firmencode',
                       'CKSBNR': 'sachbearbeiternr',
                       'CKBLST': 'blockstatus',
                       'CKVART': 'verarbeitungsart',
                       'CKRJOB': 'startjob',
                       'CKJTYP': 'jobtyp',
                       'CKANFD': 'start_date',
                       'CKANFZ': 'start_time',
                       'CKENDD': 'ende_date',
                       'CKENDZ': 'ende_time',
                       'CKECOD': 'beendigungscode',
                       'CKBLMK': 'blockstepmarkierung',
                       'CKJKEN': 'jobkennung',
                       'CKDTAE': 'letzte_aenderung_date',
                       'CKZTAE': 'letzte_aenderung_time',
                       'CKDFSL': 'dateifuehrungsschluessel',
                       'CKSTAT': 'satzstatus',
                       },
              'AVA00': {
                       #'VAFNR':  Firma
                       'VAKDNR': 'kundennr',
                       'VAVANR': 'versandadresssnr',
                       #'VAFGRP'  Firmen-Gruppe
                       #'VAAGRP'  Abteilungs-Gruppe/Sparte
                       #'VAABT'  Abteilungs-nr
                       'VASANR': 'satznr', # gepackt
                       #'VAX3VS'  Versandarten-Schlüssel
                       #'VAX3LB'  Lieferbedingungs-Schlüssel
                       #'VAINFO'  Interne Information
                       #'VAVRT'  Vertreter-nr
                       #'VAEXPR'  Expressgut-Station
                       #'VATRNR'  Auslieferungstour
                       'VAILN': 'ILN',
                       #'VARES1'  Reserve 1
                       #'VAIK01'  Indv1 1A
                       #'VAIK02'  Indv2 1A
                       #'VAIK03'  Indv3 1A
                       #'VAIK04'  Indv4 1A
                       #'VAIK05'  Indv5 1A
                       #'VAIK06'  Indv1 3A
                       #'VAIK07'  Indv2 3A
                       #'VAIK08'  Indv3 3A
                       #'VAIK09'  Indv4 3A
                       #'VAIK10'  Indv5 3A
                       #'VAIK11'  Indv 10A
                       #'VAIK12'  Indv 20A
                       #'VADTER'  Datum Erfassung CJJMMTT
                       #'VADTAE'  Datum l. Änderung CJJMMTT
                       #'VADFSL'  Dateiführungs-Schlüssel
                       'VASTAT': 'satzstatus',
                     },
              'XXA00': {
                      # 'XAFNR ': Firma
                      'XAKDNR': 'kundennr',
                      # 'XAKZKD': Kz Kunde
                      # 'XALINR': Lieferanten-nr
                      # 'XAKZLI': Kz Lieferant
                      # 'XAKZIT': Kz Interessent
                      # 'XANRRS': Freie nr
                      # 'XAKZRS': Kz Adress-Art
                      # 'XAKZT1': Adresstyp 1
                      # 'XAKZT2': Adresstyp 2
                      'XANAME': 'name1',
                      'XANAM2': 'name2',
                      'XANAM3': 'name3',
                      'XANAM4': 'name4',
                      'XASTR ': 'strasse',
                      'XAPLZ ': 'plz',
                      # 'XAPLZP': PLZ Postfach
                      # 'XAPLZF': PLZ Firma
                      # 'XAPLZI': Postleitzahl/international
                      'XAORT ': 'ort',
                      # 'XAORTT': Ortsteil/Info
                      'XALKZ ': 'laenderkennzeichen',
                      # 'XAPSTF': Postfach
                      # 'XAORTP': Ortsname (Postfach-PLZ)
                      # 'XAGESF': Gesch{ftsf}hrer
                      'XATELF': 'telefon',
                      # 'XATELX': Telex-nr
                      'XATFAX': 'fax',
                      # 'XAALSO': Alpha-Sortierfeld
                      # 'XASPSL': Sprache
                      # 'XAWSL ': W{hrungs-Kennzeichen
                      # 'XAFGRP': Firmen-Gruppe
                      # 'XAKGRP': Kunden-Gruppe
                      # 'XALGRP': Lieferanten-Gruppe
                      # 'XAISIC': ISIC-Schl}ssel
                      # 'XARPMK': RPM-Kreis
                      # 'XARPMS': RPM-Segment
                      # 'XAGDE ': Gemeindeschl}ssel
                      # 'XAHEA ': Herkunftsart
                      # 'XAHESP': Herkunftsspezifikation
                      # 'XAKZDR': Reserve 1
                      # 'XAKZR2': Reserve 2
                      # 'XAKZR3': Reserve 3
                      # 'XAKXR4': Reserve 4
                      # 'XAKZR5': Reserve 5
                      # 'XARES6': Reserve 6
                      # 'XARXS7': Reserve 7
                      # 'XARES8': Reserve 8
                      # 'XARES9': Reserve 9
                      'XASANR': 'satznr',
                      # 'XADTSP': Datum "Gesperrt bis"
                      # 'XASBSP': Sachbearbeiter Sperre
                      # 'XAKZSP': Kennzeichen Gesperrt
                      # 'XAGRSP': Grund f}r Sperre
                      # 'XATOFN': Niederlassungsk}rzel
                      # 'XATOFK': TOF Kundennr
                      # 'XATOFB': Barcodenr TOF
                      # 'XAVRT ': Vertreter f}r Interessenten
                      'XAEMAL': 'email',
                      'XAMOBI': 'mobil',
                      # 'XAHOME': Homepage
                      # 'XANAM5': 5. Namenszeile
                      # 'XANAM6': 6. Namenszeile
                      # 'XASTR2': Stra~enzusatz
                      # 'XASBER': Sachb. Erfassung
                      # 'XABPER': BenutzerPr.Erfassung
                      'XADTER': 'erfassung_date',
                      # 'XASBAE': Sachb.letzte ¢nderung
                      # 'XABPAE': BenutzerPr.letzte ¢nderung
                      'XADTAE': 'aenderung_date',
                      # 'XADFSL': Dateif}hrungs-Schl}ssel
                      'XASTAT': 'satzstatus',
                     },




}

# maps datefield to related timefield for generating datetime objects
DATETIMEDIR = {'LKDTLF': 'LKZTLF', # letzter_lieferschein
               'LKDTKB': 'LKZTKB', # letzter_kommissionierbeleg
               'LKDTER': 'LKZTER', # erfassung
               'LKDTAE': 'LKZTAE', # aenderung
               'LNDTLT': 'LNJWLT', # liefertermin
               'LNDTLF': 'LNZTLF', # lieferschein
               'LNDTER': 'LNZTER', # erfassung
               'LNDTAE': 'LNZTAE', # aenderung
               'IKDATE': 'IKTIME',
               'LNDTKB': 'LNZTKB',
               'IZDTWZ': 'IZTIME',
               'SKDTAE': 'SKZTAE', # komponenten
               'CKANFD': 'CKANFZ', # XCK00 start
               'CKENDD': 'CKENDZ', # XCK00 ende
               }
