#!/usr/bin/env python
# encoding: utf-8
"""
fields.py - describes the SoftM table structure. Part of huSoftM.

Created by Maximillian Dornseif on 2007-03-18. Based on code named "MoftS" from Summer 2005.
Copyright (c) 2007, 2008 HUDORA GmbH. All rights reserved.
"""

__revision__ = "$Revision$"

MAPPINGDIR = {
'AAK00': {# Auftragsköpfe
          # 'AKFNR ': 'Firma',
          'AKAUFN': 'auftragsnr',
          'AKSBNR': 'sachbearbeiter',
          # 'AKABT ': 'Abteilungs-nr',
          # 'AKAGRP': 'Abteilungs-Gruppe/Sparte',
          # 'AKFGRP': 'Firmen-Gruppe',
          'AKAUFA': 'art',
          # 'AKRANR': 'Rahmenvereinbarungs-Nr.',
          # 'AKKANR': 'Übergeordneter Auftrag',
          # 'AKFNRM': 'Mandanten-nr',
          # 'AKKDNR': 'Kunden-nr/Warenempfänge',
          # 'AKKDN3': 'Kunden-Nr/Verbraucher',
          # 'AKEGCD': 'Ländercode / EG',
          # 'AKUSTN': 'USt-Id-nr',
          # 'AKVANR': 'Versandadress-Nr.',
          # 'AKALS1': 'Alphasortierung/Warenempfän',
          # 'AKKDRG': 'Kundennr.Rechnungs-Empfänge',
          # 'AKALS2': 'Alphasortierung/Rech-Empfän',
          # 'AKVERB': 'Verband/Mischkonto',
          # 'AKABEM': 'Ab-Empfänger: R = Rg-Zahler',
          # 'AKRGEM': 'Rechnungsempfänger',
          'AKNRKD': 'auftragsnr_kunde',
          'AKDTKD': 'auftragsdatum_kunde',
          # 'AKDTLE': 'Leih-Datum',
          'AKDTKW': 'kundenwunsch_date',
          # 'AKJWKW': 'Kundenwunschtermin CJJWW',
          # 'AKPROB': 'Objekt/Projekt/Aktion',
          # 'AKDTVA': 'Valuta-Datum/Erfassung',
          # 'AKVALT': 'Abstandstage Valuta',
          'AKDTLT': 'liefer_date',
          'AKIK01': 'fixtermin',
          # 'AKJWLT': 'Liefertermin CJJWW',
          # 'AKX3ZB': 'Zahlungsbedingungs-Schlüsse',
          # 'AKX3VA': 'Versandarten-Schlüssel',
          # 'AKX3LB': 'Lieferbedingungs-Schlüssel',
          # 'AKVPKE': 'Verpackungskosten',
          # 'AKVSKE': 'Versandkosten',
          # 'AKNBKE': 'Nebenkosten',
          # 'AKX4NB': 'Textschl. Nebenkosten',
          # 'AKNBT1': 'Zus. Nebenkosten 1',
          # 'AKNTY1': 'Typ/Zus. Nebenkosten 1',
          # 'AKX4N1': 'Textschl. zus. Nebenkosten',
          # 'AKNBT2': 'Zus. Nebenkosten 2',
          # 'AKNTY2': 'Typ/Zus. Nebenkosten 2',
          # 'AKX4N2': 'Textschl. zus. Nebenkosten',
          # 'AKRBP1': 'Auftrags-Rabatt-%-1',
          # 'AKRBP2': 'Auftrags-Rabatt-%-2',
          # 'AKX3R1': 'Textschl. Rabatt 1',
          # 'AKX3R2': 'Textschl. Rabatt 2',
          # 'AKKZRX': 'Kz.Rabatt Brutto',
          # 'AKMWKZ': 'Umsatz-Steuerprofil',
          # 'AKWSL ': 'Währungs-Kennzeichen',
          # 'AKKURS': 'Wechsel-Kurs',
          # 'AKKUFA': 'Kursfaktor',
          # 'AKSPSL': 'Sprache',
          # 'AKVRT1': 'Vertreter 1',
          # 'AKVRT2': 'Vertreter 2',
          # 'AKPRZA': 'Aufteilungs-%-Satz',
          # 'AKBZRG': 'Bezogene RG-nr',
          # 'AKLGN1': 'Auslieferungslager',
          # 'AKLGN2': 'Zugangslager',
          # 'AKTRNR': 'Touren-nr',
          # 'AKLINR': 'Lieferant bei Strecke',
          # 'AKSPED': 'Spediteur',
          # 'AKKZBE': 'Steuerung Best.-Druck',
          # 'AKKZST': 'Kennzeichen Streckengeschäf',
          # 'AKKZWS': 'WZ/RE-Sperre',
          # 'AKKZIN': 'Kennzeichen interner Beleg',
          # 'AKKZBO': 'Steuerung Bonus-Abrechnung',
          'AKKZTF': 'teillieferung', # bzw. Teilfakturierung
          # 'AKKZSR': 'Kz.Drucken in Sammelrech=1',
          # 'AKKZZF': 'un-/versteuert',
          'AKKZVA': 'voll_ausgeliefert',
          # 'AKKZZU': 'Kz.Bevorzugte Zuteilung',
          # 'AKKZRK': 'Kz: Rückstand möglich',
          # 'AKKZSL': 'Kz.Sammel-Lieferschein',
          # 'AKKZNN': 'Kz.Nachnahme',
          # 'AKKZAR': 'Kz.Leihart',
          # 'AKABTP': 'Abt. für Prüfung KD-Zusatz',
          # 'AKDTER': 'Datum Erfassung CJJMMTT',
          # 'AKZTER': 'Uhrzeit der Erfassung',
          # 'AKDTAE': 'Datum l. Änderung CJJMMTT',
          # 'AKZTAE': 'Uhrzeit letzte Änderung',
          # 'AKDTAB': 'Datum letzte Auftragsbestät',
          # 'AKDTLF': 'Datum letzter Lieferschein',
          # 'AKDTKB': 'Datum ltzt.Kommissionierbel',
          # 'AKDTFA': 'Datum letzte Rechnung/Gutsc',
          # 'AKKZAE': 'AB: nur geänderte Posit.',
          # 'AKFKZA': 'Formular-KZ AB',
          # 'AKFKZK': 'Formular-KZ Kommission.Bele',
          # 'AKFKZL': 'Formular-KZ Lieferschein',
          # 'AKFKZR': 'Formular-KZ Rechnung/Gutsch',
          # 'AKSFAA': 'AB Sofort',
          'AKSFAL': 'LF Sofort',
          'AKSFAK': 'Komm.-Beleg sofort',
          # 'AKSFAR': 'RG Sofort',
          # 'AKABCO': 'Anzahl AB',
          'AKKBCO': 'anzahl_kommissionierbelege',
          'AKLSCO': 'anzahl_liefscheine',
          # 'AKRGCO': 'Anzahl Rechnungen',
          # 'AKOQZO': 'Outqueue-Zuordnung',
          # 'AKGEB ': 'Gebiet',
          # 'AKBRAN': 'Branche',
          # 'AKPLZ':  'plz',
          'AKLKZ': 'land',
          # 'AKVRG1': 'Vertriebs-Gruppe 1',
          # 'AKVRG2': 'Vertriebs-Gruppe 2',
          # 'AKDSTK': 'Distrikt',
          # 'AKAWRT': 'Auftragswert',
          # 'AKSTOR': 'Kennzeichen Stornierung',
          # 'AKFORM': 'Rechnungsart',
          # 'AKMJBU': 'Buchungsmonat',
          # 'AKKZWR': 'Kz wertmäßig',
          # 'AKKZVS': 'Vertriebsstatus',
          # 'AKFA1A': 'Preisstufe',
          # 'AKFA2A': 'Fax-Zustellung',
          # 'AKFA4A': 'Herkunft',
          # 'AKKZRE': 'Retouren-Beleg ja/nein',
          # 'AKKZSH': 'Hrst Strecke',
          # 'AKDTRV': 'Rahmen: gültig ab',
          # 'AKDTRB': 'Rahmen: gültig bis',
          # 'AKKDN1': 'Adresse 1',
          # 'AKKDN2': 'Adresse 2',
          # 'AKZUOR': 'Zuordnung für dezentrale An',
          # 'AKDFSL': 'Dateiführungs-Schlüssel',
          # 'AKSTAT': 'satzstatus'
         },

'AAP00': { # Auftragspositionen
          'APMNG-APMNGF-APMNGG': 'menge_offen',
           # 'APFNR ': 'Firma',
           # 'APAUFN': 'Auftrags-nr',
           'APAUPO': 'position',
           'APSBNR': 'sachbearbeiter',
           # 'APABT':  'Abteilungs-nr',
           # 'APAGRP': 'Abteilungs-Gruppe/Sparte',
           # 'APFGRP': 'Firmen-Gruppe',
           # 'APFNRX': 'Best.-Führungsfirma',
           # 'APKDNR': 'Kunden-nr',
           # 'APKDRG': 'Kundennr.Rechnungs-Empfänge',
           # 'APVERB': 'Verband/Mischkonto',
           # 'APLINR': 'Lieferanten-nr',
           # 'APAUFA': 'AUFTRAGS-ART',
           # 'APHPTP': 'zugeordnete_position',
           # 'APRANR': 'rahmenauftrag',
           # 'APRAPO': 'rahmenposition',
           # 'APKANR': 'Übergeordneter Auftrag',
           # 'APANNR': 'Angebots-nr',
           # 'APANPO': 'Angebots-Positions-nr',
           # 'APBSTN': 'Bestell-nr',
           # 'APBSTP': 'Bestell-Position',
           # 'APLHNR': 'LH-Nr.',
           # 'APLHPO': 'Leihauftrags-Pos',
           'APVGNR': 'vorgangs_nr',
           'APVGPO': 'vorgangs_position',
           # 'APFAUN': 'Fertigungsauftrag',
           # 'APPROB': 'Objekt/Projekt/Aktion',
           'APARTN': 'artnr',
           # 'APARTG': 'Artikel-Gruppe',
           # 'APARTH': 'Artikel-Haupt-Gruppe',
           # 'APKZSO': 'Kennzeichen Sonderartikel',
           'APLGNR': 'lager',
           # 'APLGRP': 'Lagergruppe',
           # 'APLGPL': 'Lager-Platz',
           # 'APKZBE': 'Ohne Bestandsführung',
           # 'APKZSE': 'Serien-/Chargenartikel',
           'APKZKO': 'komponentenaufloesung',
           'APKZPS': 'Positionsbezogener Set',
           # 'APKZEP': 'KZ: Eigen-Produkt',
           # 'APKZMU': 'Muster-Artikel',
           'APMNG': 'bestellmenge',               # Die Menge, die der Kunde haben will
           'APMNGL': 'Menge zu liefern',
           'APMNGG': 'Menge/Liefersch.nichtfakt',
           'APMNGF': 'Fakturierte Menge',          # Menge, die geliefert und fakturiert ist
           'APMNGR': 'Menge AFA35',
           'APMNGB': 'Bestellmenge in ME XLF',
           'APMESL': 'Mengen-Einheit',
           'APMEKZ': 'ME XLF/AAP',
           # 'APDEZI': 'Anzahl Dezimalstellen',
           # 'APVOLM': 'Inhalt VKE/Gebinde',
           # 'APGANZ': 'Bestellte Gebinde',
           # 'APGANF': 'Fakturierte Gebinde',
           # 'APGANG': 'Gebinde/Lief.nicht fakt',
           # 'APGANL': 'Gebinde/zu liefern',
           # 'APGANP': 'Gebinde verpackt',
           # 'APGANR': 'Gebinde AFA35',
           # 'APGEWI': 'Gewicht',
           'APPREV': 'Verkaufs-Preis',
           # 'APPEBN': 'Ebene Preisfindung',
           # 'APKZPR': 'Preiskennzeichen Verkauf',
           # 'APMEPR': 'Preis-Einheit',
           # 'APFAPR': 'Faktor APMEH --> APMEPR',
           'APFWRT': 'fakturierter Wert',
           'APOWRT': 'offener Auftragswert',
           'APPREL': 'Listen-Preis',
           # 'APPREE': 'Einstands-Preis',
           # 'APPRKZ': 'Preiskennzeichen Lager',
           # 'APWSLE': 'Währungsschlüssel: EK',
           # 'APKURS': 'Wechselkurs EK',
           # 'APKUFA': 'Kursfaktor/EK',
           # 'APRBP1': 'Pos-Rabatt-1',
           # 'APRBP2': 'Pos-Rabatt-2',
           # 'APRBP3': 'Pos-Rabatt-3',
           # 'APRBP4': 'Pos-Rabatt-4',
           # 'APKZR1': 'Berechnung Rabatt 1',
           # 'APKZR2': 'Berechnung Rabatt 2',
           # 'APKZR3': 'Berechnung Rabatt 3',
           # 'APKZR4': 'Berechnung Rabatt 4',
           # 'APX3R1': 'Textschl. Rabatt 1',
           # 'APX3R2': 'Textschl. Rabatt 2',
           # 'APX3R3': 'Textschl. Rabatt 3',
           # 'APX3R4': 'Textschl. Rabatt 4',
           # 'APKZRU': 'Kz.Rabatt versteckt',
           # 'APKZRX': 'Kz.Rabatte Brutto',
           # 'APKZRB': 'Kz: kein Auftragsrabatt = 1',
           # 'APKZET': 'Steuerung Sortiments-Rabatt',
           # 'APKZSR': 'Sortiments-Rabatt gewährt',
           # 'APMWAR': 'Steuerart / Artikel',
           'APDTLT': 'liefer_date',
           # 'APJWLT': 'Liefertermin CJJWW',
           'APDTKD': 'kundenwunsch_date',
           # 'APJWKD': 'Kundenwunschtermin CJJWW',
           'APDTLN': 'neuliefer_date',
           # 'APJWLN': 'Liefertermin neu CJJWW',
           # 'APKZTE': 'Kz: Termin-Format: 1 =WW/JJ',
           # 'APKZAB': 'Position in AB gedruckt',
           'APKZAE': 'geaendert',
           # 'APKZST': 'Kennzeichen Streckengeschäf',
           # 'APKZFA': 'Rg-Freigabe',
           # 'APKZEK': 'Schnittstelle Einkauf',
           # 'APKZBD': 'Steuerung Best.-Druck',
           # 'APKZSP': 'KZ: Sperre für Übernahme',
           # 'APHERK': 'Herkunft',
           # 'APKZSS': 'Kz Stapelschnittstelle',
           # 'APFA1A': 'Lieferschein-Auslösung',
           # 'APKZLA': 'Lieferschein-Auslösung 2',
           # 'APLFKZ': 'Kz. Lfsch drucken',
           'APKZZL': 'zuteilungskennzeichen',
           'APKZFG': 'KB/LS-Feigabe',
           'APKZRE': 'Lieferschein -Auslösung',
           # 'APKZZU': 'Kz.Bevorzugte Zuteilung',
           'APKZLF': 'Kz:Im LfSchein andrucken',
           # 'APKZVL': 'Vorab-Lieferschein',
           # 'APKZRD': 'Kz:Pos in Rech.nicht andr.=',
           # 'APKZSF': 'Kz: In Sofort-Form andrucke',
           # 'APKZSV': 'Zusätzliches Sofortformular',
           # 'APKZSA': 'Kz: keine AE-Statistik = 1',
           # 'APKZSM': 'Kz:keine Mengen-Statistik=1',
           # 'APKZSU': 'Kz:keine Umsatzstatistik=1',
           # 'APKZBA': 'Kz: kein Auftragsbestand=1',
           # 'APKZRK': 'Kz: Rückstand erlaubt = 1',
           'APKZVA': 'voll_ausgeliefert',
           # 'APKZAF': 'Kz:Abruf aus Rahmenauftrag',
           # 'APKZRA': 'Kz:Rahmen-Pos',
           # 'APKZPA': 'Kz:Preisänderung = 1',
           'APKZTA': 'Kz:Terminänderung = 1',
           'APKZMA': 'Kz:Mengenänderung = 1',
           # 'APPRVK': 'Provisions-Kennzeichen',
           # 'APPWRT': 'Provisionswert',
           # 'APPRV1': 'Provisions-%-Satz 1',
           # 'APPRV2': 'Provisions-%-Satz 2',
           # 'APGATG': 'Garantie-Tage',
           # 'APX4TR': 'Transaktions-Code',
           # 'APKZBO': 'Kz Bonus',
           # 'APKZEE': 'Einstandspreis eingebbar',
           # 'APKTO ': 'Erlöskonto',
           # 'APKTOK': 'Kosten-Konto',
           # 'APKST ': 'Kostenstelle',
           # 'APKTR ': 'Kostenträger',
           # 'APZUOR': 'Zuordnung für dezentrale An',
           # 'APRES1': 'Firma/Herkunft',
           # 'APFA3A': 'Bestell-Zusammenfass./Dispo',
           'APFA4A': 'Teil-Zuteilungs-Verbot',
           # 'APKZBF': 'ZUSATZANGABE RAHMEN/ABRUF',
           # 'APDRKZ': 'Preisdruck',
           # 'APHLKZ': 'Kz Hochregal',
           # 'APHLCR': 'Chargenrein',
           # 'APPGSZ': 'Preisstufe',
           # 'APUAPR': 'Typ Preisfaktor',
           # 'APMEGB': 'Mengeneinheiten-Schlüssel',
           # 'APSFRG': 'Pos für SofortRg ausgewählt',
           # 'APKZDI': 'Beschaffungsschlüssel',
           # 'APKZVS': 'Vertriebsstatus',
           # 'APDTRV': 'Rahmen: gültig ab',
           # 'APDTRB': 'Rahmen: gültig bis',
           # 'APAUPS': 'bezogene Position',
           # 'APSNPF': 'StzNr Preisfindung',
           'APMG01': 'Menge 1',
           # 'APWR01': 'Preis 1',
           # 'APPR01': '%-Satz 1',
           'APDTZU': 'Datum Zuteilung',
           'APZTZU': 'Uhrzeit Zuteilung HHMMSS',
           'APJNZU': 'Jobnr Zuteilung',
           # 'APDTER': 'Datum Format CJJMMTT',
           # 'APZTER': 'Uhrzeit der Erfassung',
           # 'APDTAE': 'Datum Format CJJMMTT',
           # 'APZTAE': 'Uhrzeit letzte Änderung',
           # 'APSBAE': 'Sachb.letzte Änderung',
           # 'APDFSL': 'Dateiführungs-Schlüssel',
           # 'APSTAT': 'Satzstatus',
          },

'AAT00': {# Auftragsnr
          'ATAUFN': 'auftragsnr',
          'ATAUPO': 'auftragsposition',
          'ATTART': 'textart',
          'ATLFNR': 'nr',
          'ATTX60': 'text',
          'ATKZAB': 'andruck_ab',
          'ATKZLF': 'andruck_ls',
          'ATKZRG': 'andruck_re',
         },

'AKZ00': {# Kundenstamm für Auftragsverwaltung
          'KZKDNR': 'Kunden-nr',
          #'KZSBNR': 'zuständiger Sachbearbeiter',
          'KZVRT': 'vertreter',
          'KZGEB': 'gebiet',
          'KZBRAN': 'branche',
          'KZDSTK': 'distrikt',
          #'KZKZVB':' Kz. 'Kunde ist Verbraucher','
          #'KZKZZU': 'Bevorzugte Zuteilung',
          #'KZKZRK': 'Rückstand möglich',
          'KZX3LB': 'lieferbedingung',
          'KZX3VP': 'verpackungsvorschrift',
          'KZX3VS': 'versandart',
          #'KZVANR': 'Versand-Adress Nr.',
          #'KZEXPR': 'Expreßgut-Station',
          'KZLGNR': 'auslieferunglager',
          #'KZX3ZB': 'Zahl.-Bed-Schl.',
          #'KZKDRG': 'Rechnungs-Zahler',
          #'KZWSL ': 'Währungs-Kennzeichen',
          #'KZKZBO': 'Bonus-Kennzeichen',
          #'KZKZSL': 'Sammellieferschein',
          #'KZKZRV': 'Rechnung nur vollständig',
          #'KZKZSR': 'Sammelrechnung',
          #'KZKZAB': 'Steuerung AB-Andruck',
          #'KZABCO': 'Formular-Anz./Auftragsbest.',
          #'KZKBCO': 'Formularanz./ Komm.-Beleg',
          #'KZLSCO': 'Formularanz./ Lieferschein',
          #'KZRGCO': 'Formularanz./ Rechnung',
          #'KZTELF': 'tel',
          #'KZTFAX': 'fax',
          'KZINFO': 'sachbearbeiter',
          'KZDTAE': 'updated_at',
},

'ALK00': {# Lieferscheinköpfe
          'LKSANK': 'satznr',
          'LKSANB': 'bezogener_kopf',
          'LKSBNR': 'sachbearbeiter',
          'LKLGNR': 'lager',
          'LKX3VA': 'versandart',
          'LKKZTF': 'teilfakturiert',
          'LKKDRG': 'rechnungsempfaenger',
          'LKKDNR': 'warenempfaenger',
          'LKLFSN': 'lieferscheinnr',
          'LKDTLF': 'letzter_lieferschein_date',
          'LKZTLF': 'letzter_lieferschein_time',
          'LKDTST': 'lieferschein_storno_date',
          'LKKZSL': 'sammellieferschein',
          'LKKZLF': 'druckkennzeichen',
          'LKKBNR': 'kommissionierbelegnr',
          'LKDTKB': 'letzter_kommissionierbeleg_date',
          'LKZTKB': 'letzter_kommissionierbeleg_time',
          'LKLFDN': 'laufendenr',
          'LKBELN': 'belegnr_freigabe',
          # 'LKFGNR': 'Freigabenr AFA20
          # 'LKFGSB': 'Sachbearb. Freigabe
          'LKDTFG': 'freigabe_date',
          'LKZTFG': 'freigabe_time',
          'LKFGI1': 'freigabe_info1',
          'LKFGI2': 'freigabe_info2',
          #'LKFGLC': 'Anzahl Liefsch.'
          'LKAUFS': 'auftragsnr',
          'LKDTLT': 'liefer_date',
          'LKKZ02': 'hrl_status',
          'LKKZVA': 'alle_positionen_fakturiert',
          'LKDTER': 'erfassung_date',
          'LKZTER': 'erfassung_time',
          'LKDTAE': 'aenderung_date',
          'LKZTAE': 'aenderung_time',
          'LKDFSL': 'dateifuehrungsschluessel',
          'LKSTAT': 'satzstatus',
         },

'ALN00': {# Lieferscheinpositionen
          'LNSANK': 'satznr_kopf',
          'LNSANP': 'satznr',
          # 'LNKANR': 'Übergeordnete Auftrags-Nr.
          'LNAUFN': 'auftragsnr',
          'LNAUPO': 'auftrags_position',
          'LNARTN': 'artnr',
          'LNKZKO': 'setartikel',
          'LNBSTN': 'bestellnr',
          'LNBSTP': 'bestellposition',
          # 'LNVKE':  'verkaufseinheit', # ist immer leer
          'LNLGNR': 'lager',
          #'LNLGPL': 'lagerplatz', # ist immer leer
          #'LNKZBE': 'Kz:keine Bestandsführung =1
          'LNMNGO': 'menge_offen',
          'LNDTLT': 'liefertermin_date',
          #'LNJWLT': 'liefertermin_woche',
          'LNKZRK': 'rueckstand_erlaubt',
          #'LNKZZL': 'zuteilungskennzeichen',
          'LNKZZU': 'bevorzugte_zuteilung',
          'LNKDRG': 'rechnungsempfaenger',
          'LNKDNR': 'kundennr',
          'LNLFSN': 'lieferscheinnr',
          'LNMNGL': 'menge',
          'LNDTLF': 'lieferschein_date',
          'LNZTLF': 'lieferschein_time',
          #'LNKZVL': 'KZ. Vorab-Lieferschein
          #'LNKZLD': 'Kz: Im LF. andrucken
          #'LNKZL2': 'Kz: Im LF. andrucken
          #'LNKZLF': 'Kz: LF-Schein drucken
          #'LNKZFA': 'Kz:Pos.für Fakt.ausgewählt=
          #'LNKZFF': 'Kz: Pos ist fakturierbar =
          'LNDTST': 'storno_date',
          #'LNKZRE': 'lieferschein_ausloesung',
          'LNKBNR': 'kommissionierbelegnr',
          'LNMNGK': 'menge_komissionierbeleg',
          'LNDTKB': 'komissionierbeleg_date',
          'LNZTKB': 'komissionierbeleg_time',
          'LNKZKB': 'komissionierbeleg_drucken',
          'LNRGST': 'rechnungsstatus',
          'LNDTVS': 'versand_date',
          'LNSTOR': 'gutschrift',
          'LNBELP': 'kommissionierbeleg_position',
          #'LNFGNR': 'Freigabenr AFA20
          #'LNFNFA': 'Fehlernr FG. AFA20
          'LNLSTO': 'lieferscheinstorno',
          'LNMNGF': 'menge_fakturierung',
          'LNKZV2': 'voll_ausgeliefert',
          #'LNPSTA': 'Packstatus
          #'LNKZVS': 'Kz versandfertig
          #'LNPROG': 'Herkunftsprogramm
          #'LNKZUB': 'Übernahmekennzeichen
          #'LNKINF': 'Kennzeicheninfo
          #'LNAUPS': 'bezogene Position
          #'LNKZ03': 'hrl_status',
          #'LNRSN1': 'Druck-Kz für KB
          'LNDTER': 'erfassung_date',
          'LNZTER': 'erfassung_time',
          'LNDTAE': 'aenderung_date',
          'LNZTAE': 'aenderung_time',
          'LNDFSL': 'dateiführungsschluessel',
          'LNSTAT': 'satzstatus',
          'LNSBNR': 'sachbearbeiter_bearbeitung',
         },

'AFK00': # Rechnungsköpfe
     {
     'FKFNR ': 'firma',
     # 'FKABT ': 'Abteilungs-Nummer',
     # 'FKAGRP': 'Abteilungs-Gruppe/Sparte',
     # 'FKFGRP': 'Firmen-Gruppe',
     # 'FKSBNR': 'Sachbearbeiter-Nummer',
     'FKAUFN': 'auftragsnummer',
     # 'FKKANR': '!bergeordneter Auftrag',
     # 'FKRANR': 'Rahmenvereinbarungs-Nr.',
     'FKAUFA': 'auftragsart',
     # 'FKSRKO': 'KZ SAMMELRECHNUNGS-KOPF-SAT',
     'FKRGNR': 'rechnungsnr',
     # 'FKRGNI': 'IntRg',
     # 'FKRGLI': 'Rechnungslisten-Nr.',
     # 'FKBZRG': 'Bezogene Rg',
     'FKFORM': 'rechnungsart',
     'FKSTOR': 'storniert',
     # 'FKRART': 'Rechnungsart/Rg-Freigabe',
     # 'FKKZWE': 'Kz. wertm{~iger Vorgang',
     # 'FKDTRI': 'Rechnungsdatum/intern',
     # 'FKMJBU': 'Buchungsmonat CJJMM',
     # 'FKFNRM': 'Mandanten-Nummer',
     # 'FKKDNR': 'Kunden-Nr/Warenempf{nger',
     # 'FKKDRG': 'Kunden-Nr/Rechnungsempf{nge',
     # 'FKKDN3': 'Kunden-Nr/Verbraucher',
     # 'FKVERB': 'Kunden-Nr/Verband',
     # 'FKSPSL': 'Sprache',
     # 'FKBRAN': 'Branche',
     # 'FKGEB ': 'Gebiet',
     # 'FKDSTK': 'Distrikt',
     # 'FKPLZ ': 'Postleitzahl',
     # 'FKLKZ ': 'L{nderkennzeichen',
     # 'FKNRKD': 'Kunden-Auftrags-Nummer',
     # 'FKDTKD': 'Kunden-Auftrags-Datum',
     # 'FKALS1': 'Alphasortierung/Warenempf{n',
     # 'FKALS2': 'Kennzeichen ZFB',
     # 'FKVRT ': 'Vertreter 1',
     # 'FKVRT2': 'Vertreter 2',
     # 'FKPRZA': 'Aufteilungs-%-Satz',
     # 'FKLGN2': 'Zugangslager',
     # 'FKVANR': 'Versandadress-Nr.',
     # 'FKPROB': 'Objekt/Projekt/Aktion',
     # 'FKRBP1': 'Auftrags-Rabatt-%-1',
     # 'FKRBP2': 'Auftrags-Rabatt-%-2',
     # 'FKX3R1': 'Textschl. Rabatt 1',
     # 'FKX3R2': 'Textschl. Rabatt 2',
     # 'FKKZRX': 'Kz.Rabatt Brutto',
     # 'FKTRNR': 'Touren-Nummer',
     # 'FKKZTF': 'Kennzeichen Teilfakt/Lief.',
     # 'FKKZZF': 'un-/versteuert',
     # 'FKKZRK': 'Kz: R}ckstand m¦glich',
     # 'FKKZNN': 'Kz.Nachnahme',
     # 'FKKZAR': 'Kz.Leihart',
     # 'FKKZSR': 'Sammelrechnungs-Turnus',
     # 'FKKZSD': 'Auswahl: Druck in Sammel-Rg',
     'FKBRUT': 'brutto',
     # 'FKSBRT': 'Skontierf{higer Betrag/Brt',
     # 'FKSKTA': 'Skonto-Abzugsbetrag',
     'FKNETT': 'netto',
     # 'FKMWBT': 'Mehrwert-Steuer-Betrag',
     # 'FKNETR': 'Positionswert f}r Auftr.-Ra',
     # 'FKRBB1': 'Auftragsrabatt 1',
     # 'FKRBB2': 'Auftragsrabatt 2',
     # 'FKGERB': 'Gesamt-Rabatt',
     # 'FKNBK ': 'Nebenkosten',
     # 'FKNBT1': 'Zus. Nebenkosten 1',
     # 'FKNBT2': 'Zus. Nebenkosten 2',
     # 'FKVPK ': 'Verpackungskosten',
     # 'FKVSK ': 'Versandkosten',
     # 'FKWSL ': 'W{hrungs-Kennzeichen',
     # 'FKKURS': 'Wechsel-Kurs',
     # 'FKKUFA': 'Kursfaktor',
     # 'FKMWSA': 'Umsatz-Steuerprofil',
     # 'FKEGCD': 'L{ndercode / EG',
     # 'FKUSTN': 'USt-Id-Nummer',
     # 'FKSTSL': 'Umsatz-Steuerprofil',
     # 'FKDTVF': 'Valutadatum',
     # 'FKX3ZF': 'Zahlungsbed.-Schl}ssel',
     # 'FKX3VA': 'Versandart',
     # 'FKX4NB': 'Textschl. Nebenkosten/Erf.',
     # 'FKNTY1': 'Typ/Zus. Nebenkosten 1',
     # 'FKNTY2': 'Typ/Zus. Nebenkosten 2',
     # 'FKX4N1': 'Textschl. zus. Nebenkosten',
     # 'FKX4N2': 'Textschl. zus. Nebenkosten',
     # 'FKX3LB': 'Lieferbedingung',
     # 'FKFKZR': 'KZ Rechnung drucken',
     # 'FKRGCO': 'Anzahl Rechnungen',
     'FKDTVS': 'versand_date',
     # 'FKKZRE': 'Retouren-Beleg ja/nein',
     # 'FKKZUF': 'Auswahldaten -->  AAK00',
     # 'FKKZUS': 'Update Statistikdaten',
     # 'FKSANK': 'Satznummer Kopf',
     # 'FKPROG': 'Herkunftsprogramm',
     # 'FKSNLK': 'Satznummer ALK00',
     # 'FKFBEL': 'Beleg-Nummer f}r Freigabe',
     # 'FKFAUF': 'Auftrags-Nr. f}r Freigabe',
     'FKDTFA': 'druck_date',
     # 'FK30ST': 'Kz Fakt.Update Statistik',
     # 'FK30FI': 'Kz Fakt.Update FIBU',
     # 'FKKZBB': 'Status FIBU-Verbuchung',
     # 'FKKZRV': 'Kz Rechnungsvorb. erforderl',
     # 'FKKZKD': 'Nachtr. Erstellung / 9 = ja',
     # 'FKKZKS': 'Steuerung Kundenstrecke',
     # 'FKKZTL': 'Andruck in Tourenliste',
     # 'FKTRPO': 'Pos-Nummer/Tourenliste',
     # 'FKTRLN': 'Nr Tourenl.',
     # 'FKDTTL': 'Datum/Tourenliste',
     # 'FKLDLN': 'Nr Ladel.',
     # 'FKLDLP': 'PosNr Ladeliste',
     # 'FKKZLL': 'Kz. Ladeliste',
     # 'FKDTLL': 'Datum/Ladeliste',
     'FKKZIB': 'interner_beleg',
     # 'FKKZRL': 'Andruck in Rg-Liste',
     # 'FKKZPR': 'Abgleich  FIBU/Statistik',
     # 'FKKZSE': 'Ausg.SEDAS-Schnittstelle',
     # 'FKOQZO': 'Outqueue-Zuordnung',
     # 'FKZUOR': 'Zuordnung f}r dezentrale An',
     # 'FKKZ01': 'Packstatus Beleg',
     # 'FKKZ05': 'Sort SmlRg',
     # 'FKSORT': 'Sortierfeld',
     # 'FKSNRG': 'StzNr SmlRg',
     # 'FKDFSL': 'Dateif}hrungs-Schluessel',
     'FKSTAT': 'status',
     'FKDTER': 'erfassung_date',
     'FKZTER': 'erfassung_time',
     },


'AFU00': # Rechnungspositionen
        {
        'FUFNR': 'firma',
        'FURGNR': 'rechnungsnr',
        # 'FURGNI': 'Intern Rechnungs-Nr.',
        # 'FUAUFN': 'Auftrags-Nummer',
        # 'FUAUPO': 'Auftrags-Position',
        # 'FUPOZU': 'Zusatz-Position',
        # 'FUABT ': 'Abteilung/Auftrag',
        # 'FUKDNR': 'Kunden-Nr/Warenempf{nger',
        # 'FUKDRG': 'Kunden-Nr/Rechnungsempf{nge',
        # 'FUFNRX': 'Best.-F}hrungsfirma',
        'FUARTN': 'artnr',
        # 'FUARTG': 'Artikel-Gruppe',
        # 'FUARTH': 'Artikel-Haupt-Gruppe',
        # 'FULGNR': 'Lager',
        # 'FULGRP': 'Lagergruppe',
        # 'FULGPL': 'Lager-Platz',
        'FUMNG': 'menge',
        # 'FUMESL': 'MENGENEINHEIT/STAT.',
        # 'FUPNET': 'Positions-Netto-Wert',
        # 'FUPBUT': 'Positions-Brutto-Wert',
        # 'FUPORB': 'Positions-Rabatt-Betrag',
        # 'FUPREW': 'Wert/Ek',
        # 'FUPREV': 'Verkaufs-Preis',
        # 'FUPEBN': 'Ebene Preisfindung',
        # 'FUKZPR': 'Preiskennzeichen Verkauf',
        # 'FUMEPR': 'Preis-Einheit',
        # 'FUFAPR': 'Faktor APMEH --> APMEPR',
        # 'FUPREE': 'Einstands-Preis',
        # 'FUWSLE': 'W{hrungsschl}ssel: EK',
        # 'FUPRDL': 'Preiskennzeichen Lager',
        # 'FUKUFA': 'Kursfaktor/EK',
        # 'FUKURS': 'Wechselkurs EK',
        # 'FUMWAR': 'Steuerart / Artikel',
        # 'FUDEZI': 'Anzahl Dezimalstellen',
        # 'FUKZBE': 'Ohne Bestandsf}hrung',
        # 'FUKZST': 'Kennzeichen Streckengesch{f',
        # 'FUKZKO': 'Mit Komponentenaufl¦sung',
        # 'FUKZRB': 'Kz: kein Auftragsrabatt = 1',
        # 'FUKZRD': 'Kz:Pos in Rech.nicht andr.=',
        # 'FUKZRU': 'Kz.Rabatt versteckt',
        # 'FUKZRX': 'Kz.Rabatte Brutto',
        # 'FUKZSE': 'Serien-/Chargenartikel',
        # 'FUKZSO': 'Kennzeichen Sonderartikel',
        # 'FUKZPS': 'Positionsbezogener Set',
        # 'FUPRKZ': 'Preiskennzeichen Lager',
        # 'FUKZEP': 'KZ: Eigen-Produkt',
        # 'FUKZZU': 'Zuschlagssatz',
        # 'FUGANZ': 'Bestellte Gebinde',
        # 'FUVOLM': 'Volumen/Inhalt',
        # 'FUGEWI': 'Gewicht',
        # 'FULFSN': 'Lieferschein-Nr./7-stellig',
        # 'FUDTLF': 'Datum/LfS-Druck',
        # 'FUDTFA': 'Datum/Rechungsdruck',
        # 'FUKZRV': 'Kz Rechnungsvorb. erforderl',
        # 'FUFKZR': 'Kennzeichen Rechnung drucke',
        # 'FU30ST': 'Kz Fakt.Update Statistik',
        # 'FU30FI': 'Kz Fakt.Update FIBU',
        # 'FULBUF': 'Kz.Lagerbuchung fehlt',
        # 'FUSORT': 'Sortierfeld',
        # 'FUSANK': 'Satznummer Kopf',
        # 'FUSANP': 'Satznummer',
        # 'FUPROG': 'Herkunftsprogramm',
        # 'FUSNLN': 'Satznummer ALN00',
        # 'FUSNST': 'Satznummer Statistik',
        # 'FUSANR': 'Bezogene Bewegung',
        # 'FURES1': 'Reserve-Feld-01',
        # 'FURES2': 'Reserve-Feld-02',
        # 'FURES3': 'Packstatus BlgPos',
        # 'FURES5': 'Reserve-Feld-05',
        # 'FUBTR1': 'Reserve-Feld-Betrag 1',
        # 'FUBTR2': 'Reserve-Feld-Betrag 2',
        # 'FUKZ02': 'EstdPrs XSL',
        # 'FUAUPS': 'bezogene Position',
        # 'FUSNRG': 'StzNr SmlRg',
        # 'FUDTRI': 'Rechnungsdatum/intern',
        'FUDTER': 'erfassung_date',
        'FUZTER': 'erfassung_time',
        },


'ASK00': {# Set/Komponenten
           # 'SKFNR':  'firma',
           'SKARTN': 'artnr',
           # 'SKAUFN': 'Auftrags-nr',
           # 'SKAUPO': 'Auftrags-Position',
           'SKLFNR': 'laufende_nr',
           'SKKART': 'komponenten_artnr',
           'SKMENG': 'menge_im_set',
           # 'SKKZSE': 'KENNZ: SERIEN-NR.-ARTIKEL',
           # 'SKKZ01': 'AbwStddSet',
           # 'SKKZ02': 'Kz. ohne Bestandsf.',
           # 'SKKZ03': 'Auf/Ang',
           # 'SKPROZ': 'Anteil am Umsatz in %',
           # 'SKKZPD': 'Kz PrFnd',
           # 'SKHPTP': 'NatRbPos',
           # 'SKDTAE': 'updated_at_date',
           # 'SKZTAE': 'updated_at_time',
           },

'AVA00': {
         #'VAFNR':  Firma
         'VAKDNR': 'kundennr',
         'VAVANR': 'versandadresssnr',
         #'VAFGRP'  Firmen-Gruppe
         #'VAAGRP'  Abteilungs-Gruppe/Sparte
         #'VAABT'  Abteilungs-nr
         'VASANR': 'satznr', # gepackt
         #'VAX3VS'  Versandarten-Schlüssel
         #'VAX3LB'  Lieferbedingungs-Schlüssel
         #'VAINFO'  Interne Information
         #'VAVRT'  Vertreter-nr
         #'VAEXPR'  Expressgut-Station
         #'VATRNR'  Auslieferungstour
         'VAILN': 'iln',
         #'VADTER'  Datum Erfassung CJJMMTT
         #'VADTAE'  Datum l. Änderung CJJMMTT
         #'VADFSL'  Dateiführungs-Schlüssel
         'VASTAT': 'satzstatus',
       },

'BED00': { # Datei fuer die Zentrale-Meldung innerg. Warenverk.
          'EDFNR ': 'firmennr',
          'EDPKTO': 'personenkonto',
          'EDBEKZ': 'berichtigungskennzeichen',
          # 'EDJHBU': '???',
          'EDJJBU': 'buchungsjahr',
          'EDQUAR': 'meldequartal',
          'EDEGCF': 'egcd_fremde_firma',
          'EDUSTF': 'ustnr_fremde_firma',
          'EDEGCE': 'egcd_eigene_firma',
          'EDUSTE': 'ustnr_eigene_firma',
          'EDBEMG': 'bemessgrundlage',
          'EDKZ  ': 'warenbewegungskennzeichen',
          'EDKZDR': 'kennzeichen_dreiecksgeschaeft',
          'EDRAFF': 'geraffte_daten',
          'EDA01A': 'buchhaltungskennzeichen',
          # 'EDRBT ': 'reserve_betrag',
          'EDSTBT': 'steuerbetrag',
          },

'EBP00': { # Bestellpositions-Datei
          'BPMNGB-BPMNGL': 'menge_offen',
          # 'BPFNR ': 'Firma',
          'BPBSTN': 'bestellnr',
          'BPBSTP': 'position',
          # 'BPBSAB': 'Nummer des bez. Rahmenvert.',
          # 'BPBSAP': 'Pos-Nr des bez. Rahmenvert.',
          # 'BPTGAR': 'Tage bis Druck Abr-Pos',
          'BPSBNR': 'created_by',
          'BPSBAE': 'updated_by',
          # 'BPABT ': 'Abteilungs-Nummer',
          # 'BPAGRP': 'Abteilungs-Gruppe/Sparte',
          # 'BPFGRP': 'Firmen-Gruppe',
          # 'BPHPOS': 'Nr Hauptposition',
          # 'BPBDIF': 'Tg BeschffgT. - DeckgT.',
          # 'BPANNR': 'Anfrage',
          # 'BPANPO': 'Anfrageposition            ' ,
          'BPARTN': 'artnr',
          # 'BPLIAR': 'Lieferanten-Artikel-Nr     ' ,
          # 'BPARTG': 'Artikel-Gruppe             ' ,
          # 'BPARTH': 'Artikel-Haupt-Gruppe       ' ,
          'BPLGNR': 'lager',
          # 'BPWERK': 'Werksnummer                ' ,
          # 'BPEMPF': 'Empfangsstelle             ' ,
          # 'BPKZSO': 'KZ: Sonderartikel          ' ,
          # 'BPKZBE': 'KZ: Ohne Bestandsf}hrung   ' ,
          # 'BPFNRK': 'Fnr/Zugriff Lief-Adresse   ' ,
          'BPLINR': 'lieferant',
          # 'BPHRST': 'Hersteller                 ' ,
          # 'BPFNRZ': 'zentrale Einkaufsfirma     ' ,
          # 'BPFNRR': 'Firma f}r Rahmen',
          # 'BPHERK': 'KZ: Herkunft',
          # 'BPURSA': 'Verursacher',
          # 'BPSBN2': 'Zust{ndiger Eink{ufer',
          # 'BPSBN5': 'Anfordernder Sachbearbeiter',
          # 'BPINFN': 'Informationsnummer',
          # 'BPINFA': 'Informationsnummernart',
          # 'BPPRVO': 'Pr}f-Vorschriften-Nr',
          # 'BPMEER': 'Mengeneinheit der Bestellun',
          # 'BPFAKT': 'Umrechn.-Faktor  ER-->BE',
          # 'BPMEBE': 'Mengeneinheit/Bestandsf.',
          # 'BPDEZI': 'Anzahl Dezimalstellen',
          # 'BPKTO ': 'Konto',
          # 'BPKTR ': 'Kostentr{ger',
          # 'BPUKTR': 'Kostentr{gerunternummer    ' ,
          # 'BPKST ': 'Kostenstelle               ' ,
          # 'BPPROJ': 'Projekt                    ' ,
          # 'BPUPRJ': 'Projektunternummer         ' ,
          # 'BPFABG': 'Leistungsart/FremdArbGang  ' ,
          # 'BPKZFG': 'Fremdarbeitsgangart        ' ,
          # 'BPX3VP': 'Verpackungsvorschrift      ' ,
          # 'BPLIAU': 'Lieferanten-Auftrags-Nummer' ,
          # 'BPWSL ': 'W{hrung/Bestellpreis       ' ,
          'BPPREW': 'wert',
          # 'BPKZWR': 'Preisdimension             ' ,
          # 'BPPRAK': 'Tats{chlicher Preis        ' ,
          # 'BPPREB': 'Best{tigter Preis          ' ,
          # 'BPNANZ': 'Anzahl Rabatte             ' ,
          # 'BPPREH': 'Bestellpreis/Hauptw{hrung  ' ,
          # 'BPWRTF': 'Abgerufener Positionswert  ' ,
          # 'BPWRTR': 'Summe Rabatte              ' ,
          # 'BPWRTN': 'Summe Nebenkosten          ' ,
          # 'BPMNGE': 'Bestell-Menge/Bestell-Eh   ' ,
          # 'BPMNG3': 'Menge vor ¢nder./Bestell-Eh' ,
          # 'BPMNG4': 'Best{tigte Menge/Best-Eh   ' ,
          'BPMNGB': 'bestellmenge',
          'BPMNGL': 'gelieferte_menge',
          # 'BPMNG1': 'Vorabgebuchte gelief. Menge' ,
          # 'BPMNGA': 'Reserviert f}r Auftr{ge    ' ,
          # 'BPMNGF': 'Gebuchte berechnete Menge  ' ,
          # 'BPMNG2': 'nicht mehr verwendet       ' ,
          # 'BPMNGO': 'Ausschu~-Menge             ' ,
          # 'BPMNGQ': 'Menge Qual-Lager',
          # 'BPMSTU': 'Mahnstufe',
          # 'BPKZMI': 'Mahn-Inhalt',
          # 'BPKZLA': 'Mahn Lief-AB',
          # 'BPTGLE': 'Tg.Lief.Erinnerung',
          # 'BPTYP ': 'Bestelltyp',
          # 'BPTART': 'Feld 2 1A',
          # 'BPKZVT': 'SSt Einkauf/Auftrag',
          'BPKZDT': 'wunsch_date',
          # 'BPKZFA': 'Art Fremdarbeitgang',
          # 'BPKZCZ': 'Chargenzertifikat',
          # 'BPKZEK': 'Feld 2 1/0',
          # 'BPKZNP': 'KZ Nebenposition',
          # 'BPKZPZ': 'Positionszusatz',
          # 'BPKZUL': 'Unlimitiert',
          # 'BPKZBP': 'KZ: Bestellbestand/Periode',
          # 'BPKZAB': 'KZ: Bestell-Abschlu~',
          # 'BPKZQU': 'KZ: Qualit{tspr}fung',
          # 'BPKZAE': 'KZ: Position ge{ndert',
          # 'BPKZAK': 'KZ: Abgeschlossen',
          # 'BPKZAR': 'KZ: Rahmen / Abruf',
          # 'BPKZDR': 'Bereits im Formular gedruck',
          # 'BPKZAD': 'KZ: Artikel-Nr andrucken',
          'BPKZGL': 'geliefert_kz',
          # 'BPPZGL': '%-Satz VollGeliefert',
          # 'BPKZTF': 'KZ: Teillieferung erlaubt',
          # 'BPKZUE': 'KZ: Unter-/!berlieferung',
          # 'BPPZUE': '%-Satz erlaubte !nter/!berL',
          # 'BPKZIE': 'KZ: Intern/Extern',
          # 'BPKZLE': 'KZ: Liefererinnerung drucke',
          # 'BPKZMA': 'KZ: In Mahnung andrucken',
          # 'BPKZPP': 'Kz: Pr}fpflichtig',
          # 'BPKZPR': 'Kz: Gesch{tzter Preis',
          # 'BPKZSP': 'Sperre f}r Bestellandruck',
          # 'BPKZWZ': 'KZ: Warenzugang nicht buche',
          # 'BPKZTX': 'KZ: Textart',
          # 'BPKZLT': 'KZ: Art Liefertermin',
          # 'BPKZMB': 'KZ: Materialbeistellung',
          # 'BPKZAL': 'KZ: EAL00 versorgen',
          # 'BPKZTA': 'KZ: im TA verarbeitet',
          # 'BPKZBM': 'KZ Dialog',
          'BPKZSG': 'streckengeschaeft',
          # 'BPKZSI': 'Kz: Sperre / inaktiv',
          # 'BPSPLT': 'KZ Splitting',
          # 'BPLIZF': 'KZ Lieferantenzertifizierun',
          # 'BPKEYI': 'Kd-Individueller Schl}ssel',
          'BPDTLT': 'liefer_date',
          # 'BPWWLT': 'Liefertermin/Woche',
          # 'BPDTRV': 'Rahmen g}ltig von',
          # 'BPDTRB': 'Rahmen g}ltig bis',
          # 'BPDTLE': 'Datum Liefererinnerung',
          # 'BPDTMA': 'Datum letzte Mahnung',
          # 'BPDTBD': 'Datum letzter Bestellandruc',
          'BPDTWU': 'wunsch2_date',
          'BPDTBE': 'termin1_date',
          'BPDTBL': 'termin2_date',
          'BPDTLZ': 'zugang_date',
          # 'BPDTER': 'erfassung_date',
          # 'BPDTAE': 'aenderung_date',
          # 'BPDTAL': 'Datum der Lieferanten-AB',
          'BPDFSL': 'dateifuehrungsschluessel',
          'BPSTAT': 'status',
           },

# TODO: wird IET00 noch genutzt?
'IET00': { # Etikettendruckdatei
          'ETSANR': 'satznr',
          'ETARTN': 'artnr',
          'ETBEZ1': 'bezeichnung1',
          'ETBEZ2': 'bezeichnung2',
          'ETLGPA': 'lagerplatzAn',
          'ETDTBE': 'datumBearbeitung',
          'ETMNGI': 'vorgangsMenge',
          #'ETBSTN': 'Bestellummer',
          #'ETBSTP': 'Bestellposition',
          #'ETAUFN': 'KdAuftrag',
          #'ETAUPO': 'KdAuftragspos',
          # 'ETKZVG': 'vorgangskennz',
          # 'ETKZHK': 'vorgangsherkunft',
          # 'ETETNR': 'EtikettenNr',
          #'ETANZ':  'Anzahl Etiketten',
          'ETDRET': 'druck',
          'ETDTER': 'erfassung_date',
          'ETSBER': 'sachbearbeiter_erfassung',
          'ETDTAE': 'aenderung_date',
          'ETSBAE': 'sachbearbeiter_aenderung',
          'ETDFSL': 'dateifuehrungsschluessel',
          'ETSTAT': 'satzstatus',
          },

'ISA00': {# MyPL Schnittstelle: Komissionierbeleg
          'IAFNR': 'firma',
          'IALGNR': 'lagernr',
          'IAKBNR': 'kommissionierbelegnr',
          'IAAUFN': 'auftragsnr',
          'IADATE': 'anforderung_date',
          'IATIME': 'anforderung_time',
          'IADFSL': 'dateifuehrungsschluessel',
          'IASTAT': 'status',
          'IASANR': 'satznr',
         },

'ISB00': {# MyPL Schnittstelle: Lagerbuchungsschnittstelle
          'IBFNR': 'firma',
          'IBBWSL': 'bewegungsschluessel',
          'IBLGNR': 'lager',
          'IBARTN': 'artnr',
          'IBMNGB': 'menge',
          'IBINFO': 'info',
          'IBFCOD': 'letzter_fehlercode',
          'IBDFSL': 'dateifuehrungsschluessel',
          'IBSTAT': 'status',
         },

'ISK00': {# MyPL Schnittstelle: Warenzugang aus Umlagerung
          'IKFNR': 'firma',
          'IKKBNR': 'kommissionierbelegnr',
          'IKKPOS': 'kommissionierbelegposition',
          'IKAUFN': 'auftragsnr',
          'IKAUPO': 'auftragsposition',
          'IKRMNG': 'rueckmeldemenge',
          'IKDATE': 'rueckmeldung_date',
          'IKTIME': 'rueckmeldung_time',
          'IKDFSL': 'dateifuehrungsschluessel',
          'IKSTAT': 'status',
          'IKSANR': 'satznr',
         },

'ISR00': {# MyPL Schnittstelle: KB-Rückmeldung
          'IRFNR': 'firma',
          'IRKBNR': 'kommissionierbelegnr',
          'IRKPOS': 'kommissionierbelegposition',
          'IRAUFN': 'auftragsnr',
          'IRAUPO': 'auftragsposition',
          'IRMENG': 'rueckmeldemenge',
          'IRKZNU': 'kennzeichen_nullen',
          'IRKZST': 'kennzeichen_stornieren',
          'IRFCOD': 'letzter_fehlercode',
          'IRDFSL': 'dateifuehrungsschluessel',
          'IRSTAT': 'status',
         },

'ISZ00': {# MyPL Schnittstelle: Warenzugang aus Auftrag
          'IZFNR ': 'firma',
          'IZBSTN': 'bestellnr',
          'IZWVNR': 'warenvereinnahmungsnr',
          'IZDTWZ': 'zugang_date',
          'IZTIME': 'zugang_time',
          'IZDFSL': 'dateiführungsschlüssel',
          'IZSTAT': 'status',
          'IZSANR': 'satznr',
          },

'XAD00': {# Abweichende Lieferadressen
          'ADNAME': 'name1',
          'ADNAM2': 'name2',
          'ADNAM3': 'name3',
          'ADNAM4': 'name4',
          'ADSTR': 'strasse',
          'ADPLZ': 'plz',
          'ADORT': 'ort',
          'ADLKZ': 'laenderkennzeichen',
          #'ADORTT': 'ortsteil',
          'ADKZAD': 'adressaufbereitung',
         },

'XAR00': {# Artikelstamm
           'ARARTN': 'artnr',
           'ARSTAT': 'status',
           'ARARTH': 'artikelhauptgruppe',
           'ARARTG': 'artikelgruppe',
           'ARBEZ1': 'ARBEZ1',
           'ARBEZ2': 'ARBEZ2',
           'ARBEZ3': 'ARBEZ3',
           'ARGEWI': 'gewicht',
           'ARNGEW': 'gewicht_netto',
           'AREAN': 'ean',
           'ARMEBE': 'mengeneinheit',
           'ARZOGR': 'zollgruppe',
           'ARZTNR': 'statistischewarennr',
           'ARPREV': 'listenpreis',
           'ARMALG': 'laenge',
           'ARMABR': 'breite',
           'ARMATI': 'tiefe',
           'AREART': 'ersatzartikel',
           'ARMCOD': 'matchcode',
           #'ARMEBE': 'Mengeneinheit/Bestandsf.',
           #'ARMEER': 'Mengeneinheit/Erfassung',
           #'ARFAKT': 'Umrechn.-Faktor  ER-->BE',
           #'ARMEPR': 'Mengeneinheit/Preis',
           #'ARFAPR': 'Umrechn.-Faktor  PR-->BE',
           'ARABC': 'abc1',
           'ARABC2': 'abc2',
           'ARABC3': 'abc3',
           #'ARZOGR': 'Zoll-Grupppe-nr',
           'ARZTNR': 'zolltarifnr',
           'ARURLD': 'ursprungsland',
           #'ARPREV': 'Verkaufspreis',
           #'ARPRE2': 'Verkaufspreis 2',
           #'ARPREA': 'Verkaufspreis Ausland',
           #'ARPRI2': 'Vk-Preis/Inland - neu -',
           #'ARPRA2': 'Vk-Preis/Ausland - neu -',
           #'ARDTPI': 'Ab Datum Vk/Inland - neu -',
           #'ARDTPA': 'Ab Datum Vk/Ausland - neu -',
           #'ARPGSZ': 'Preisgruppen-Staffel-Zuordn',
           #'ARWSL' : 'Währungs-Kennzeichen',
           #'ARRBPR': 'Artikel-Rabatt-%-Satz',
           #'ARKZKW': 'Ohne wertmäßige Best.-Führ.',
           'ARKZKO': 'setartikel',
           'ARKZVK': 'verkaufsteil',
           #'ARKZNE': 'Kennzeichen Neuheit',
           #'ARDTNA': 'Auslieferungs-Datum/Neuheit',
           'ARKZNA': 'auslaufartikel',
           'ARKZAT': 'artikeltexte_vorhanden',
           'ARVKUB': 'volumen',
           'ARKZZS': 'zuteilungssperre',
           'ARINFO': 'info',
           'ARMGMA': 'mindestabnahmemenge',
           'ARCTAR': 'ersatzteil',
           'ARKZVP': 'ist_verpackung',
           #'ARKZWB': 'webshop',
           #'ARHAFO': 'handelsform',
           #'ARDAFO': 'darreichungsform',
           #'ARKZRG': 'andruck_in_rechnung',
           'ARSBER': 'Sachb. Erfassung',
           'ARBPER': 'BenutzerPr.Erfassung',
           'ARSBAE': 'Sachb.letzte Änderung',
           'ARBPAE': 'BenutzerPr.letzte Änderung',
           'ARDTER': 'erfassung_date',
           'ARDTAE': 'aenderung_date', },

'XCK00': { # Ablaufkontrolle
          'CKJNUM': 'jobnr',
          'CKBLNA': 'blockname',
          'CKJNAM': 'jobname',
          'CKUSER': 'benutzer',
          'CKWSID': 'bildschirmidentifikation',
          'CKFNR ': 'firmennr',
          'CKFCOD': 'firmencode',
          'CKSBNR': 'sachbearbeiternr',
          'CKBLST': 'blockstatus',
          'CKVART': 'verarbeitungsart',
          'CKRJOB': 'startjob',
          'CKJTYP': 'jobtyp',
          'CKANFD': 'start_date',
          'CKANFZ': 'start_time',
          'CKENDD': 'ende_date',
          'CKENDZ': 'ende_time',
          'CKECOD': 'beendigungscode',
          'CKBLMK': 'blockstepmarkierung',
          'CKJKEN': 'jobkennung',
          'CKDTAE': 'letzte_aenderung_date',
          'CKZTAE': 'letzte_aenderung_time',
          'CKDFSL': 'dateifuehrungsschluessel',
          'CKSTAT': 'satzstatus',
          },

'XED00': { # Intrastat-Meldungs-Datei
            'EDINKZ': 'kennziffer',
            'EDFORM': 'anmeldeform',
            'EDSITZ': 'sitz_versender_empfaenger',
            'EDMONA': 'anmeldemonat',
            'EDFIL1': 'fueller01',
            'EDPOS ': 'paginiernr',
            'EDFIL2': 'fueller02',
            'EDBLFA': 'bundesland_finanzamt',
            'EDSTNR': 'steuernr',
            'EDUSNR': 'unterscheidungsnr',
            'EDLCOD': 'bestimmungsland',
            'EDBLND': 'ursprungsbundesland',
            'EDGSCH': 'art_des_geschaefts',
            'EDVKZW': 'verkehrszweig',
            'EDFIL3': 'fueller03',
            'EDPORT': 'hafen_flughafen',
            'EDFIL4': 'fueller04',
            'EDSTWN': 'statistische_warennr',
            'EDFIL5': 'fueller05',
            'EDFIL6': 'fueller06',
            'EDVERF': 'statistisches_verfahren',
            'EDGEWI': 'einganmasse_in_kg',
            'EDMNGX': 'besondere_masseinheit',
            'EDFIL7': 'fueller07',
            'EDWRWA': 'warenwert_netto',
            'EDWRGU': 'statistischer_wert',
            'EDFIL8': 'fueller08',
            'EDBUMM': 'bezugsmonat',
            'EDBUJJ': 'bezugsjahr',
            'EDKREI': 'mineraloelerhebungspreis',
            'EDFIL9': 'fueller09',
          },

'XKD00': {# Kundenadressen
          'KDKDNR': 'kundennr',
          'KDNAME': 'name1',
          'KDNAM2': 'name2',
          'KDNAM3': 'name3',
          'KDNAM4': 'name4',
          'KDSTR': 'strasse',
          'KDPLZ': 'plz',
          'KDORT': 'ort',
          'KDLKZ': 'laenderkennzeichen',
          'KDTELF': 'tel',
          'KDTFAX': 'fax',
          'KDMOBI': 'mobil',
          'KDPSTF': 'postfach', # gelegentlich genutzt
          'KDPLZP': 'postfach_plz', # wenig genutzt
          #'KDORTP': 'Ortsname (Postfach-PLZ)', # gelegentlich genutzt
          #'KDPLZF': 'PLZ Firma', # sehr wenig genutzt
          # 'KDGESF': 'Geschäftsführer', # wenig genutzt
          'KDALSO': 'sortierfeld',
          # 'KDSPSL': 'Sprache', # Werte 1 & 2
          # 'KDWSL ': 'Währungs-Kennzeichen',
          'KDKGRP': 'kundengruppe', # alphanum
          'KDEMAL': 'mail',
          'KDHOME': 'url',
          'KDSANR': 'adressdatei_id',
          'KDDTER': 'erfassung_date',
          'KDDTAE': 'aenderung_date',
          },

'XKS00': { # Kundenzusatzdaten
          'KSKDNR': 'kundennr',
          'KSLISP': 'liefersperre',
          'KSAWRT': 'offener_aftragswert',
          'KSAKWR': 'kreditlimit',
          'KSCOMP': 'company',
          'KSIAKZ': 'inland_ausland',
          'KSFNRK': 'interne_firmennr',
          'KSINFL': 'unsere_lieferantennumemr',
          'KCUSTN': 'ustid',
          'KSLIMI': 'kreditlimit2',
          'KSSKSL': 'skontoschluessel',
          'KSDKSL': 'delcredereschlüssel',
          'KSMASP': 'mahnsperre',
          'KSKDZA': 'lastschrift',
          'KSBOKZ': 'bonnitaet',
          # 'KSKLTA': 'Kd/Li-Texte anzeigen',
          # 'KSINF1': 'Inf. 1',
          'KCVERB': 'verband',
          #'KSKRED': 'Verbands-/Mischkto-Satz',
          'KCMGVB': 'mitgliednr',
          #'KCBBN':  'Bundeseinheitl.Betriebsnr.',
          #'KCBBS':  'Bundeseinh.Betriebsstell.Nr',
          #'KCVRKZ': 'Kz. "Rechnungsliste erst."',
          #'KCRGKZ': 'Kz. "Rechnung drucken"',
          #'KCKOIN': 'Kontoinhaber',
          #'KCHSTU': 'Auswertungsebene / KD-Hier',
          #'KCSKRL': 'Skto-Ausweis RGL Verband',
          #'KCEDIL': 'LS-Daten per EDI',
          #'KCPRIA': 'Inlands-/Auslandspreise',
          'KCE2IL': 'iln',
          },

'XXA00': {
        # 'XAFNR ': Firma
        'XAKDNR': 'kundennr',
        # 'XAKZKD': Kz Kunde
        # 'XALINR': Lieferanten-nr
        # 'XAKZLI': Kz Lieferant
        # 'XAKZIT': Kz Interessent
        # 'XANRRS': Freie nr
        # 'XAKZRS': Kz Adress-Art
        # 'XAKZT1': Adresstyp 1
        # 'XAKZT2': Adresstyp 2
        'XANAME': 'name1',
        'XANAM2': 'name2',
        'XANAM3': 'name3',
        'XANAM4': 'name4',
        'XASTR ': 'strasse',
        'XAPLZ ': 'plz',
        # 'XAPLZP': PLZ Postfach
        # 'XAPLZF': PLZ Firma
        # 'XAPLZI': Postleitzahl/international
        'XAORT ': 'ort',
        # 'XAORTT': Ortsteil/Info
        'XALKZ ': 'laenderkennzeichen',
        # 'XAPSTF': Postfach
        # 'XAORTP': Ortsname (Postfach-PLZ)
        # 'XAGESF': Gesch{ftsf}hrer
        'XATELF': 'tel',
        # 'XATELX': Telex-nr
        'XATFAX': 'fax',
        # 'XAALSO': Alpha-Sortierfeld
        # 'XASPSL': Sprache
        # 'XAWSL ': W{hrungs-Kennzeichen
        # 'XAFGRP': Firmen-Gruppe
        # 'XAKGRP': Kunden-Gruppe
        # 'XALGRP': Lieferanten-Gruppe
        # 'XAISIC': ISIC-Schl}ssel
        # 'XARPMK': RPM-Kreis
        # 'XARPMS': RPM-Segment
        # 'XAGDE ': Gemeindeschl}ssel
        # 'XAHEA ': Herkunftsart
        # 'XAHESP': Herkunftsspezifikation
        'XASANR': 'satznr',
        # 'XADTSP': Datum "Gesperrt bis"
        # 'XASBSP': Sachbearbeiter Sperre
        # 'XAKZSP': Kennzeichen Gesperrt
        # 'XAGRSP': Grund f}r Sperre
        # 'XATOFN': Niederlassungsk}rzel
        # 'XATOFK': TOF Kundennr
        # 'XATOFB': Barcodenr TOF
        # 'XAVRT ': Vertreter f}r Interessenten
        'XAEMAL': 'mail',
        'XAMOBI': 'mobil',
        # 'XAHOME': Homepage
        # 'XANAM5': 5. Namenszeile
        # 'XANAM6': 6. Namenszeile
        # 'XASTR2': Stra~enzusatz
        # 'XASBER': Sachb. Erfassung
        # 'XABPER': BenutzerPr.Erfassung
        'XADTER': 'erfassung_date',
        # 'XASBAE': Sachb.letzte ¢nderung
        # 'XABPAE': BenutzerPr.letzte ¢nderung
        'XADTAE': 'aenderung_date',
        # 'XADFSL': Dateif}hrungs-Schl}ssel
        'XASTAT': 'satzstatus',
       },
}

# maps datefield to related timefield for generating datetime objects
DATETIMEDIR = {'LKDTLF': 'LKZTLF', # letzter_lieferschein
               'LKDTKB': 'LKZTKB', # letzter_kommissionierbeleg
               'LKDTER': 'LKZTER', # erfassung
               'LKDTAE': 'LKZTAE', # aenderung
               'LNDTLF': 'LNZTLF', # lieferschein
               'LNDTER': 'LNZTER', # erfassung
               'LNDTAE': 'LNZTAE', # aenderung
               'IKDATE': 'IKTIME',
               'LNDTKB': 'LNZTKB',
               'IZDTWZ': 'IZTIME',
               'SKDTAE': 'SKZTAE', # komponenten
               'CKANFD': 'CKANFZ', # XCK00 start
               'CKENDD': 'CKENDZ', # XCK00 ende
               }
